"use server";
import {redirect} from "next/navigation";import {requireAdmin} from "@/lib/admin/auth";import {createSupabaseAdminClient as createSupabaseServerClient} from "@/lib/supabase/admin";import {emitNotificationSafe} from "@/lib/notifications/service";
const text=(f:FormData,k:string)=>String(f.get(k)||"").trim(),required=(f:FormData,k:string)=>{const v=text(f,k);if(!v)throw new Error(`Missing ${k}`);return v};const done=(id:string,label:string)=>redirect(`/admin/clients/${id}?saved=${encodeURIComponent(label)}`);
export async function saveOverview(f:FormData){await requireAdmin("edit_clients");const db=createSupabaseServerClient(),id=required(f,"organization_id"),business=required(f,"business_id");const [org,biz]=await Promise.all([db.from("organizations").update({name:required(f,"business_name"),primary_contact_name:text(f,"contact_name")||null,primary_contact_email:text(f,"email")||null,primary_contact_phone:text(f,"phone")||null}).eq("id",id),db.from("businesses").update({name:required(f,"business_name"),industry:text(f,"industry")||null,website:text(f,"website")||null,description:text(f,"description")||null}).eq("id",business).eq("organization_id",id)]);if(org.error||biz.error)throw org.error||biz.error;done(id,"Client overview updated")}
const address=(f:FormData)=>({line1:text(f,"address"),city:text(f,"city"),state:text(f,"state"),country:text(f,"country"),postal_code:text(f,"postal_code")});
export async function saveLocation(f:FormData){await requireAdmin("edit_clients");const db=createSupabaseServerClient(),org=required(f,"organization_id"),id=text(f,"location_id"),values={business_id:required(f,"business_id"),name:required(f,"name"),address:address(f),phone:text(f,"phone")||null,timezone:text(f,"timezone")||"Asia/Kolkata",website:text(f,"gbp_url")||null,google_business_identifier:text(f,"gbp_url")||null,status:"active" as const};const result=id?await db.from("locations").update(values).eq("id",id):await db.from("locations").insert(values);if(result.error)throw result.error;done(org,id?"Location updated":"Location added")}
export async function removeLocation(f:FormData){await requireAdmin("edit_clients");const db=createSupabaseServerClient(),org=required(f,"organization_id");const {error}=await db.from("locations").update({status:"archived"}).eq("id",required(f,"location_id"));if(error)throw error;done(org,"Location removed")}
export async function addClientService(f:FormData){await requireAdmin("manage_services");const db=createSupabaseServerClient(),org=required(f,"organization_id");const {error}=await db.from("client_services").insert({organization_id:org,business_id:required(f,"business_id"),service_id:required(f,"service_id"),owner_id:text(f,"owner_id")||null,status:"setup",notes:text(f,"notes")||null});if(error)throw error;done(org,"Service assigned")}
export async function saveClientService(f:FormData){await requireAdmin("manage_services");const db=createSupabaseServerClient(),org=required(f,"organization_id"),status=required(f,"status") as "setup"|"active"|"paused"|"completed";const {error}=await db.from("client_services").update({status,owner_id:text(f,"owner_id")||null,notes:text(f,"notes")||null,completed_at:status==="completed"?new Date().toISOString():null}).eq("id",required(f,"client_service_id")).eq("organization_id",org);if(error)throw error;done(org,status==="completed"?"Service removed":"Service updated")}
export async function saveIntegration(f:FormData){await requireAdmin("manage_integrations");const db=createSupabaseServerClient(),org=required(f,"organization_id"),id=text(f,"connection_id"),raw=text(f,"metadata");let metadata={};if(raw){try{metadata=JSON.parse(raw)}catch{throw new Error("Metadata must be valid JSON")}}const values={organization_id:org,business_id:text(f,"business_id")||null,location_id:text(f,"location_id")||null,integration_id:required(f,"integration_id"),account_identifier:text(f,"account_identifier")||null,status:required(f,"status"),instructions:text(f,"instructions")||null,private_metadata:metadata,connected_at:required(f,"status")==="connected"?new Date().toISOString():null};const result=id?await db.from("integration_connections").update(values).eq("id",id).eq("organization_id",org):await db.from("integration_connections").insert(values);if(result.error)throw result.error;done(org,"Integration saved")}
export async function saveAccessTemplate(f:FormData){const actor=await requireAdmin("edit_clients"),db=createSupabaseServerClient(),org=required(f,"organization_id"),id=text(f,"template_id"),values={title:required(f,"title"),instructions:required(f,"instructions"),integration_id:text(f,"integration_id")||null,created_by:actor.userId};const result=id?await db.from("access_request_templates").update(values).eq("id",id):await db.from("access_request_templates").insert(values);if(result.error)throw result.error;done(org,"Access template saved")}
export async function sendAccessRequest(f:FormData){const actor=await requireAdmin("edit_clients"),db=createSupabaseServerClient(),org=required(f,"organization_id"),templateId=required(f,"template_id");const {data:template,error}=await db.from("access_request_templates").select("title,instructions").eq("id",templateId).single();if(error)throw error;const {error:insertError}=await db.from("client_access_requests").insert({organization_id:org,template_id:templateId,title:template.title,instructions:template.instructions,requested_by:actor.userId});if(insertError)throw insertError;const {data:members}=await db.from("organization_members").select("user_id").eq("organization_id",org).eq("status","active");await emitNotificationSafe({event:"service_assigned",recipientIds:(members||[]).map(member=>member.user_id),organizationId:org,title:template.title,body:"DigiUdyam needs access information to continue delivery."});done(org,"Access request sent")}
