"use server";
import { revalidatePath } from "next/cache";
import { addLeadActivity,archiveLead,changeLeadStatus,convertLeadToClient,createLead,deleteLead,updateLead } from "@/lib/admin/crm-service";
const value=(form:FormData,key:string)=>String(form.get(key)||"").trim();const required=(form:FormData,key:string)=>{const result=value(form,key);if(!result)throw new Error(`Missing ${key}`);return result};
const refresh=()=>{revalidatePath("/admin/crm");revalidatePath("/admin/crm/pipeline");revalidatePath("/admin")};
export async function createLeadAction(form:FormData){await createLead({name:required(form,"name"),business_name:required(form,"business_name"),email:value(form,"email")||null,phone:value(form,"phone")||null,website:value(form,"website")||null,location:value(form,"location")||null,industry:value(form,"industry")||null,lead_source:required(form,"lead_source"),notes:value(form,"notes")||null,status:"new_lead",pipeline_value:Number(value(form,"pipeline_value")||0),follow_up_at:value(form,"follow_up_at")||null,sales_owner_id:value(form,"sales_owner_id")||null});refresh()}
export async function updateLeadAction(form:FormData){await updateLead(required(form,"id"),{name:required(form,"name"),business_name:required(form,"business_name"),email:value(form,"email")||null,phone:value(form,"phone")||null,website:value(form,"website")||null,location:value(form,"location")||null,industry:value(form,"industry")||null,lead_source:required(form,"lead_source"),notes:value(form,"notes")||null,pipeline_value:Number(value(form,"pipeline_value")||0),follow_up_at:value(form,"follow_up_at")||null,sales_owner_id:value(form,"sales_owner_id")||null});refresh()}
export async function moveLeadAction(id:string,status:"new_lead"|"contacted"|"qualified"|"proposal_sent"|"negotiation"|"won"|"lost"){await changeLeadStatus(id,status);refresh()}
export async function changeLeadStageAction(form:FormData){await moveLeadAction(required(form,"id"),required(form,"status") as "new_lead"|"contacted"|"qualified"|"proposal_sent"|"negotiation"|"won"|"lost")}
export async function addLeadActivityAction(form:FormData){await addLeadActivity({leadId:required(form,"lead_id"),type:required(form,"activity_type") as "call"|"email"|"note"|"follow_up",summary:required(form,"summary")});refresh()}
export async function archiveLeadAction(form:FormData){await archiveLead(required(form,"id"));refresh()}
export async function deleteLeadAction(form:FormData){await deleteLead(required(form,"id"));refresh()}
export async function convertLeadAction(form:FormData){await convertLeadToClient({leadId:required(form,"lead_id"),locationName:required(form,"location_name"),timezone:value(form,"timezone")||"Asia/Kolkata",serviceIds:form.getAll("service_ids").map(String).filter(Boolean),accountManagerId:value(form,"account_manager_id"),specialistIds:form.getAll("specialist_ids").map(String).filter(Boolean)});refresh();revalidatePath("/admin/clients");revalidatePath("/admin/onboarding")}
