export type IndustryMoneyPage = {
  metadata:{title:string;description:string;ogTitle:string;ogDescription:string};
  hero:{heading:string;paragraphs:string[];needsHeading:string;needs:string[]};
  challenges:{heading:string;copy:string}[];
  journey:{heading:string;copy:string}[];
  solutions:{slug:string;heading:string;copy:string}[];
  connection:{heading:string;paragraphs:string[];items:string[]};
  process:{heading:string;copy:string}[];
  expectations:{heading:string;copy:string}[];
  faqs:{q:string;a:string}[];
  finalCta:{heading:string;copy:string;outcomes:string[]};
};

const clinics:IndustryMoneyPage={
  metadata:{title:"Digital Growth Solutions for Clinics in India",description:"Digital growth solutions for Indian clinics combining websites, Local SEO, Google Business Profile, CRM and practical follow-up systems.",ogTitle:"Help More Patients Find and Contact Your Clinic",ogDescription:"Build a clearer clinic discovery and enquiry journey with DigiUdyam."},
  hero:{heading:"Help Patients Find, Trust and Contact Your Clinic Online",paragraphs:["Patients often compare clinics online before they call or book. DigiUdyam helps Indian clinics build a clear digital journey—from local discovery to an organised enquiry and follow-up.","We connect the website, Google visibility and customer-management systems around how your clinic actually works. Medical decisions and patient care always remain with qualified professionals."],needsHeading:"A connected clinic growth system can help you",needs:["Present services and locations clearly","Improve visibility in relevant local searches","Make calls, messages and appointment enquiries easier","Organise enquiries and follow-ups responsibly"]},
  challenges:[{heading:"Patients cannot find clear information",copy:"Outdated hours, unclear services or missing location details can make a patient choose another clinic before contacting you."},{heading:"Discovery depends on one channel",copy:"Relying only on referrals or a single listing makes it harder to build a dependable online presence."},{heading:"Enquiries arrive in different places",copy:"Calls, forms and WhatsApp messages can become difficult to track when there is no shared process."},{heading:"Follow-ups are inconsistent",copy:"Appointment enquiries and permitted reminders may be missed when ownership and next actions are unclear."}],
  journey:[{heading:"Discovery",copy:"A patient searches on Google, Maps or another trusted source."},{heading:"Evaluate",copy:"They review your clinic website, profile, services, location and practical trust information."},{heading:"Enquiry",copy:"They call, message or submit an appointment enquiry through a clear action."},{heading:"Organisation",copy:"The enquiry is recorded in an appropriate CRM or agreed workflow with clear ownership."},{heading:"Follow-up",copy:"Your team responds and sends permitted updates or reminders while keeping human judgement in control."}],
  solutions:[{slug:"website-development",heading:"Website Development",copy:"Explain clinic services, doctors, locations, timings and enquiry options in a clear mobile-friendly experience."},{slug:"local-seo",heading:"Local SEO",copy:"Build the wider local visibility system connecting your website, location signals, listings and useful local information."},{slug:"google-business-profile",heading:"Google Business Profile",copy:"Correct and improve profile categories, services, hours, photos and customer actions."},{slug:"crm-solutions",heading:"CRM Solutions",copy:"Organise non-clinical enquiries, ownership, status and follow-up without presenting CRM as a medical-record system."},{slug:"whatsapp-automation",heading:"WhatsApp Automation",copy:"Support approved acknowledgements and reminders while leaving sensitive conversations and decisions to your team."}],
  connection:{heading:"Why clinics need these services to work together",paragraphs:["Visibility alone does not complete the patient journey. A person may discover your clinic on Maps, verify details on your website and then contact you by phone or WhatsApp.","Connecting discovery, enquiry capture and follow-up helps your team provide a clearer experience without automating medical advice or replacing personal care."],items:["Local SEO and Google Business Profile support discovery","The website provides complete, owned information","Clear contact paths turn interest into an enquiry","CRM and approved workflows help the team manage the next step"]},
  process:[{heading:"Discovery",copy:"We understand your services, locations, audience, existing presence and enquiry process."},{heading:"Planning",copy:"We identify the priority customer journey, channels, information gaps and practical scope."},{heading:"Implementation",copy:"We improve the agreed website, visibility, profile or customer-management elements."},{heading:"Tracking",copy:"We review relevant actions such as calls, messages, forms and workflow progress where tracking is available."},{heading:"Improvement",copy:"We recommend sensible updates based on observed performance, business feedback and changing priorities."}],
  expectations:[{heading:"No guaranteed enquiries or rankings",copy:"Search visibility and enquiry volume depend on location, competition, demand, reputation, budget and many external factors."},{heading:"Timelines depend on the work",copy:"Profile corrections may be visible sooner; websites, Local SEO and connected workflows require planning, implementation and ongoing improvement."},{heading:"Clinic input is essential",copy:"Your team provides accurate service, practitioner, location and policy information and approves public-facing details."},{heading:"Privacy stays important",copy:"We plan only the agreed enquiry and communication workflow. Clinical records and sensitive patient information require appropriate specialist systems and controls."}],
  faqs:[{q:"What digital marketing services are useful for a clinic?",a:"The right mix depends on how patients currently find and contact you. A clinic may need a clear website, Local SEO, Google Business Profile optimisation, enquiry organisation and approved WhatsApp follow-ups rather than disconnected marketing activities."},{q:"Can Local SEO help patients discover my clinic nearby?",a:"Local SEO can improve the accuracy, relevance and consistency of the signals that help search engines understand your clinic and location. It cannot guarantee a position, but it can strengthen how your clinic is represented in local discovery."},{q:"What should a clinic website include?",a:"It should clearly present services, practitioner information supplied by the clinic, locations, timings, contact options, appointment enquiry steps and important policies. The exact structure depends on the clinic and applicable professional requirements."},{q:"Is Google Business Profile enough for a clinic?",a:"It is an important discovery platform, but it has limited space and is not fully owned by the clinic. A website provides deeper information, while Local SEO connects the profile, website, listings and local signals."},{q:"Can you automate clinic appointment reminders?",a:"We can plan approved reminder and acknowledgement workflows where the chosen tools and clinic process support them. Automation should not provide medical advice, make clinical decisions or replace sensitive human communication."},{q:"How long does clinic digital growth take?",a:"It depends on the starting point and scope. Setup and corrections can be completed in defined phases, while search visibility, customer trust and workflow improvement are ongoing activities."}],
  finalCta:{heading:"Find the gaps in your clinic’s digital journey",copy:"Request a free audit and receive a practical review of your website, local visibility, Google Business Profile and enquiry journey.",outcomes:["Priority visibility gaps","Website and profile observations","Enquiry-path review","Recommended next actions"]}
};

const restaurants:IndustryMoneyPage={
  metadata:{title:"Digital Marketing Solutions for Restaurants in India",description:"Digital growth solutions for Indian restaurants combining websites, Local SEO, Google Business Profile, marketing and reputation support.",ogTitle:"Help More Local Customers Discover Your Restaurant",ogDescription:"Create a clearer restaurant discovery journey across search, Maps, menus, reviews and marketing."},
  hero:{heading:"Help Local Customers Discover and Choose Your Restaurant",paragraphs:["Customers often decide where to eat after checking Google, Maps, menus, photos, reviews and social content. DigiUdyam helps Indian restaurants make that journey clear and consistent.","We connect local discovery, owned information, customer actions and practical marketing so your restaurant is easier to evaluate before a customer visits, calls or reserves."],needsHeading:"A connected restaurant growth system can help you",needs:["Keep menu and business information easier to find","Improve local discovery across Google and Maps","Guide customers towards calls, directions or reservations","Build a consistent review and repeat-customer process"]},
  challenges:[{heading:"Menus and details are inconsistent",copy:"Different prices, timings or contact details across platforms create confusion at the moment a customer is deciding."},{heading:"The restaurant is hard to discover locally",copy:"Weak location signals and incomplete information can limit visibility for relevant nearby searches."},{heading:"The visual presentation is outdated",copy:"Poor photos, old menus and an unclear website can make the actual experience difficult to understand."},{heading:"Reviews and repeat visits lack a process",copy:"Feedback, responses and customer updates often happen irregularly when nobody owns the workflow."}],
  journey:[{heading:"Discovery",copy:"A customer searches by cuisine, area, occasion or sees a relevant campaign."},{heading:"Evaluate",copy:"They check Maps, menu, photos, reviews, location and the restaurant website."},{heading:"Action",copy:"They call, request directions, reserve or place an enquiry through the available channel."},{heading:"Organisation",copy:"The request reaches the right person or booking workflow with enough context."},{heading:"Return",copy:"The restaurant provides a consistent experience and may invite genuine feedback or share permitted updates."}],
  solutions:[{slug:"website-development",heading:"Website Development",copy:"Create an owned, mobile-friendly place for menus, location details, atmosphere, events and customer actions."},{slug:"local-seo",heading:"Local SEO",copy:"Connect the website, listings, location information, reviews and local relevance around how diners search."},{slug:"google-business-profile",heading:"Google Business Profile",copy:"Improve categories, hours, menu links, photos, attributes and actions on a key restaurant discovery platform."},{slug:"digital-marketing",heading:"Digital Marketing",copy:"Plan campaigns, content direction, landing experiences and measurement around specific business goals."},{slug:"reputation-management",heading:"Reputation Management",copy:"Create a responsible process for monitoring feedback, responding consistently and learning from genuine reviews."}],
  connection:{heading:"Why restaurants need these services to work together",paragraphs:["A customer rarely decides from one asset. They may discover you on Maps, check the menu on your website, compare reviews and then ask for directions or reserve.","When information, presentation and customer actions are connected, the restaurant can offer a more consistent journey across the channels customers already use."],items:["Local SEO and GBP support nearby discovery","The website keeps key information under your control","Digital marketing supports selected campaigns and occasions","Reputation management supports trust and operational learning"]},
  process:[{heading:"Discovery",copy:"We learn about your cuisine, locations, service model, audiences, busy periods and current channels."},{heading:"Planning",copy:"We map the discovery-to-visit journey and agree the highest-priority visibility and customer-action gaps."},{heading:"Implementation",copy:"We complete the agreed website, profile, local search, campaign or reputation work."},{heading:"Tracking",copy:"We review available actions such as calls, directions, website visits, reservations or campaign enquiries."},{heading:"Improvement",copy:"We update priorities using real customer behaviour, restaurant feedback and seasonal business needs."}],
  expectations:[{heading:"No guaranteed covers, leads or revenue",copy:"Demand is affected by cuisine, location, pricing, competition, service, reviews, seasonality and other business factors."},{heading:"Some work is ongoing",copy:"Profile corrections and website updates can be delivered in phases, while local visibility, campaigns and reputation need regular attention."},{heading:"Restaurant input keeps information accurate",copy:"Your team supplies and approves menus, offers, timings, policies, photographs and operational changes."},{heading:"Marketing supports the guest experience",copy:"Digital work can improve discovery and decision-making, but the in-person food and service experience remains central to repeat business."}],
  faqs:[{q:"Which digital marketing services are useful for restaurants?",a:"Many restaurants benefit from a mobile-friendly website, Local SEO, Google Business Profile optimisation and a consistent reputation process. Digital campaigns may be added for specific goals, locations, launches or occasions."},{q:"Can Local SEO help my restaurant appear on Google Maps?",a:"Local SEO strengthens the broader signals around your location, website, listings and relevance. Google Business Profile optimisation improves the profile itself. Neither can guarantee a particular Maps position."},{q:"Does a restaurant still need a website?",a:"A website gives the restaurant an owned place for current menus, locations, events, story and direct customer actions. It supports, rather than replaces, Google Maps and food or reservation platforms."},{q:"Can you help update our Google Business Profile?",a:"Yes. Depending on scope, we can review and improve categories, hours, menu and website links, photos, attributes and other available profile information with your approval."},{q:"How should restaurants manage online reviews?",a:"Use a consistent process to monitor feedback, respond politely and learn from recurring themes. Requests should seek genuine feedback and should never manufacture or selectively misrepresent reviews."},{q:"How quickly can restaurant marketing show results?",a:"Setup and corrections have defined delivery timelines, but customer response depends on the channel, offer, location and market. We set realistic expectations and review measurable actions rather than promise outcomes."}],
  finalCta:{heading:"See where your restaurant’s discovery journey can improve",copy:"Request a free audit for a practical review of your website, local visibility, Google Business Profile and customer action paths.",outcomes:["Local discovery gaps","Menu and website observations","Profile and customer-action review","Prioritised next steps"]}
};

const realEstate:IndustryMoneyPage={
  metadata:{title:"Digital Marketing Solutions for Real Estate in India",description:"Digital growth solutions for Indian real estate businesses connecting websites, marketing, CRM and automation for organised property enquiries.",ogTitle:"Turn Property Interest Into Organised Follow-up",ogDescription:"Connect property discovery, enquiry capture, CRM ownership and practical follow-up with DigiUdyam."},
  hero:{heading:"Turn Property Enquiries Into an Organised Sales Process",paragraphs:["Real estate enquiries can arrive from portals, campaigns, websites, calls and WhatsApp. Without clear capture, ownership and follow-up, genuine buyer interest can get lost between people and tools.","DigiUdyam helps Indian real estate businesses connect digital marketing with websites, CRM and practical automation—so teams can understand each enquiry and manage the next action."],needsHeading:"A connected real estate growth system can help you",needs:["Present projects and locations clearly","Capture enquiries with useful context","Assign ownership and track pipeline stages","Support timely, consistent follow-up"]},
  challenges:[{heading:"Enquiries arrive without enough context",copy:"A name and phone number alone may not explain the customer’s location, budget range, property interest or timeline."},{heading:"Lead sources are disconnected",copy:"Portal, website, ad, call and WhatsApp enquiries can be difficult to compare when each follows a separate process."},{heading:"Ownership is unclear",copy:"Without an assigned owner and visible next action, teams may respond late, duplicate outreach or miss follow-ups."},{heading:"Manual handovers slow the journey",copy:"Repeated copying between forms, sheets and messaging tools adds delay and inconsistency."}],
  journey:[{heading:"Discovery",copy:"A buyer or investor sees a relevant property, project page, search result or campaign."},{heading:"Evaluate",copy:"They review location, property details, suitability and available trust information."},{heading:"Enquiry",copy:"A focused form, call or message captures their interest and useful qualifying context."},{heading:"CRM",copy:"The enquiry is recorded, assigned and moved through an agreed sales pipeline."},{heading:"Follow-up",copy:"The sales owner completes the next action, such as clarification, a call, brochure share or site-visit planning."}],
  solutions:[{slug:"website-development",heading:"Website Development",copy:"Present projects, locations and enquiry paths through focused pages that work clearly on mobile."},{slug:"digital-marketing",heading:"Digital Marketing",copy:"Plan channels, campaigns, landing pages and measurement around defined property audiences and goals."},{slug:"crm-solutions",heading:"CRM Solutions",copy:"Organise lead sources, requirements, ownership, pipeline stages, tasks and follow-up visibility."},{slug:"automation",heading:"Business Automation",copy:"Connect forms, routing, notifications and repeatable handovers while keeping sales conversations human-led."}],
  connection:{heading:"Why real estate needs marketing and sales systems together",paragraphs:["Campaigns can create interest, but lead volume alone does not create a dependable sales process. The landing experience must capture useful context, and the team needs ownership and visibility after the enquiry arrives.","Connecting the website, marketing, CRM and selected workflows creates a clearer path from discovery to qualified human follow-up."],items:["Marketing reaches relevant audiences and measures acquisition","Website and landing pages explain the project and capture context","CRM gives each enquiry an owner, status and next action","Automation supports routing and reminders without replacing sales judgement"]},
  process:[{heading:"Discovery",copy:"We review projects, audiences, current channels, lead sources, sales stages, tools and follow-up practices."},{heading:"Planning",copy:"We map the acquisition-to-follow-up journey and define the scope, ownership and information required at each step."},{heading:"Implementation",copy:"We build or improve the agreed pages, tracking, CRM setup, integrations and workflows."},{heading:"Tracking",copy:"We review source, enquiry quality signals, response workflow and pipeline movement where reliable data is available."},{heading:"Improvement",copy:"We refine pages, campaigns and processes using actual sales-team feedback and measured behaviour."}],
  expectations:[{heading:"No guaranteed leads, sales or revenue",copy:"Results depend on project-market fit, inventory, location, pricing, audience, sales response, budget and external market conditions."},{heading:"Useful implementation happens in phases",copy:"A focused page or CRM setup may have a defined delivery period; campaigns and operational improvements need testing and ongoing review."},{heading:"The client owns business accuracy",copy:"Your team provides current inventory, approvals, project information, legal disclosures, budgets and sales-process decisions."},{heading:"Automation supports rather than replaces people",copy:"Workflows can route data and prompt next actions. Qualification judgement, negotiation and customer relationships remain with the sales team."}],
  faqs:[{q:"Which digital marketing services are useful for real estate businesses?",a:"A common system combines focused websites or landing pages, channel planning, measurable campaigns, CRM lead organisation and selected follow-up workflows. The right mix depends on the project, audience and sales process."},{q:"How does a CRM help a real estate sales team?",a:"A CRM can record enquiry source and requirements, assign an owner, show pipeline stage, schedule next actions and make follow-up visible. It organises the process; it does not replace good qualification and sales conversations."},{q:"Can DigiUdyam manage real estate lead generation campaigns?",a:"We can support strategy, campaign structure, landing-page recommendations and measurement where paid acquisition is appropriate. Media spend is separate, and no responsible provider can guarantee lead quantity or sales."},{q:"What information should a property enquiry form collect?",a:"Collect only information that helps the team respond appropriately, such as contact details, project or location interest and broad requirements. The form should stay clear, proportionate and aligned with your privacy obligations."},{q:"What can be automated in a real estate workflow?",a:"Possible workflows include form-to-CRM capture, lead routing, owner notifications, task creation and approved follow-up reminders. Sensitive conversations, qualification decisions and negotiations should remain human-led."},{q:"How long does a real estate digital system take to implement?",a:"The timeline depends on the number of projects, page requirements, CRM readiness, integrations and approvals. We define phased deliverables before implementation and separate setup work from ongoing campaign improvement."}],
  finalCta:{heading:"Find the gaps between property discovery and follow-up",copy:"Request a free audit for a practical review of your website, acquisition journey, enquiry capture, CRM organisation and follow-up workflow.",outcomes:["Acquisition and landing-page gaps","Enquiry capture observations","CRM and ownership review","Prioritised workflow actions"]}
};

const homeServices:IndustryMoneyPage={
  metadata:{title:"Digital Marketing for Home Service Businesses in India",description:"Digital growth solutions for Indian home service businesses using websites, Local SEO, Google Business Profile, CRM and automation.",ogTitle:"Help Local Customers Find and Contact Your Home Service Business",ogDescription:"Connect local discovery, quote enquiries and organised follow-up with DigiUdyam."},
  hero:{heading:"Win More Relevant Local Enquiries for Your Home Service Business",paragraphs:["Customers looking for plumbers, electricians, cleaners, repair professionals and other home services often need a nearby provider they can understand and trust quickly.","DigiUdyam connects your website, local visibility and enquiry process so customers can find the right service, confirm your service area and contact your team without confusion."],needsHeading:"A connected home-service system can help you",needs:["Show services and service areas clearly","Improve discovery in relevant local searches","Build trust before a customer requests a quote","Organise calls, messages and follow-up"]},
  challenges:[{heading:"The business is difficult to find locally",copy:"Weak service-area information and inconsistent business details can limit relevant discovery."},{heading:"Customers cannot verify the service quickly",copy:"Missing proof, unclear service descriptions or an outdated website can reduce confidence before contact."},{heading:"Enquiries arrive while the team is working",copy:"Calls, forms and messages may be missed when field work takes priority and no shared process exists."},{heading:"Quote follow-up is difficult to track",copy:"Without ownership and next actions, promising enquiries can remain in personal phones or spreadsheets."}],
  journey:[{heading:"Search",copy:"A customer searches for a specific service in their area."},{heading:"Evaluate",copy:"They review the website, Google profile, service area, business details and available trust signals."},{heading:"Enquiry",copy:"They call, message or request a quote with relevant job information."},{heading:"CRM",copy:"The enquiry is recorded, assigned and given a clear status or next action."},{heading:"Follow-up",copy:"Your team clarifies requirements, schedules the work or follows up on the quote."}],
  solutions:[{slug:"website-development",heading:"Website Development",copy:"Explain services, service areas, proof and enquiry options through a fast mobile-friendly website."},{slug:"local-seo",heading:"Local SEO",copy:"Improve the wider local search system connecting service pages, listings and location relevance."},{slug:"google-business-profile",heading:"Google Business Profile",copy:"Keep profile details, categories, hours, service areas, photos and actions useful and accurate."},{slug:"crm-solutions",heading:"CRM Solutions",copy:"Organise quote requests, ownership, customer details, status and follow-up tasks."},{slug:"automation",heading:"Business Automation",copy:"Connect forms, notifications and repeatable handovers while keeping estimates and customer conversations human-led."}],
  connection:{heading:"Why home service businesses need these services together",paragraphs:["Local visibility creates the opportunity, but customers still need clear service information and a quick path to contact the business.","A connected website, profile, CRM and workflow helps the team move from discovery to an organised quote or booking conversation."],items:["Local SEO and GBP support nearby discovery","The website explains services and coverage clearly","CRM gives each enquiry an owner and next action","Automation supports routing and reminders without replacing the team"]},
  process:[{heading:"Discovery",copy:"We review services, service areas, customer questions, current visibility and enquiry handling."},{heading:"Strategy",copy:"We prioritise the customer journey, pages, local signals and follow-up gaps that matter most."},{heading:"Implementation",copy:"We complete the agreed website, profile, search, CRM or workflow improvements."},{heading:"Tracking",copy:"We review available calls, forms, messages and workflow progress without inventing attribution."},{heading:"Improvement",copy:"We refine priorities using real enquiry patterns, team feedback and changing service needs."}],
  expectations:[{heading:"No guaranteed leads or rankings",copy:"Results depend on demand, location, competition, reputation, pricing, capacity and customer response."},{heading:"Local visibility develops over time",copy:"Business-detail corrections can be quicker, while website authority and Local SEO require consistent work."},{heading:"Accurate service information comes from you",copy:"Your team supplies current services, coverage, hours, proof, pricing guidance and approvals."},{heading:"Operations affect conversion",copy:"Digital improvements can support enquiries, but response time, availability and service quality influence whether customers proceed."}],
  faqs:[{q:"How can a home service business get found on Google locally?",a:"Start with accurate business information, clear service and service-area pages, a useful Google Business Profile and consistent local signals. The exact plan depends on the locations served and how customers search."},{q:"Do home service businesses need a website as well as Google Business Profile?",a:"Yes in many cases. The profile supports discovery, while an owned website can explain each service, service area, process and enquiry options in greater detail."},{q:"Can CRM help manage quote requests?",a:"A CRM can record the enquiry, source, job context, owner, status and next action. It helps organise follow-up but does not replace estimating or customer conversations."},{q:"Can missed enquiries be automated?",a:"Selected acknowledgements, routing and internal notifications can be automated when the tools support them. Your team should still review requirements and provide accurate quotes."},{q:"How long does Local SEO take for a home service business?",a:"There is no fixed ranking timeline. Technical and profile corrections have defined delivery periods, while local relevance, authority and visibility generally need ongoing improvement."}],
  finalCta:{heading:"Find the gaps in your local enquiry journey",copy:"Request a free audit of your website, local visibility, Google profile and enquiry follow-up process.",outcomes:["Service-area visibility review","Website and profile observations","Enquiry-path gaps","Prioritised next actions"]}
};

const beautyWellness:IndustryMoneyPage={
  metadata:{title:"Digital Marketing for Salons and Wellness Businesses India",description:"Digital growth solutions for Indian salons and wellness businesses covering websites, Local SEO, Google profiles, reviews and WhatsApp follow-up.",ogTitle:"Turn Local Discovery Into Appointments and Repeat Visits",ogDescription:"Create a clearer salon and wellness customer journey with DigiUdyam."},
  hero:{heading:"Turn Local Discovery Into Appointments and Repeat Visits",paragraphs:["Salon and wellness customers often compare location, services, photos, reviews and availability before they contact a business.","DigiUdyam helps salons, spas and wellness businesses connect local visibility, service information, reputation and practical communication around that decision journey."],needsHeading:"A connected beauty and wellness system can help you",needs:["Present treatments and services clearly","Improve discovery across search and Maps","Build trust through accurate information and genuine reviews","Support appointment and repeat-visit communication"]},
  challenges:[{heading:"Local visibility is inconsistent",copy:"Incomplete location and service information can make the business harder to discover for relevant nearby searches."},{heading:"Services are difficult to compare",copy:"Customers may leave when prices, duration, suitability or booking steps are unclear."},{heading:"Reviews lack a consistent process",copy:"Feedback may go unanswered or review requests may happen irregularly without clear ownership."},{heading:"Appointments and repeat visits rely on memory",copy:"Messages, confirmations and permitted follow-ups can become scattered across personal inboxes."}],
  journey:[{heading:"Discovery",copy:"A customer searches locally or discovers a service through digital content."},{heading:"Evaluate",copy:"They check the website, Google profile, services, photos, reviews and location."},{heading:"Enquiry",copy:"They ask about availability, pricing or suitability through a call, form or WhatsApp."},{heading:"Organisation",copy:"The request is recorded in the agreed booking or customer-management workflow."},{heading:"Follow-up",copy:"Your team confirms the next step and may send permitted reminders or relevant return-visit communication."}],
  solutions:[{slug:"website-development",heading:"Website Development",copy:"Create an owned place for services, pricing guidance, locations, team information and booking actions."},{slug:"local-seo",heading:"Local SEO",copy:"Connect website content, listings, location signals and local relevance around customer searches."},{slug:"google-business-profile",heading:"Google Business Profile",copy:"Improve categories, services, hours, photos, links and profile accuracy."},{slug:"reputation-management",heading:"Reputation Management",copy:"Build a responsible process for genuine feedback, monitoring and thoughtful responses."},{slug:"whatsapp-automation",heading:"WhatsApp Automation",copy:"Support approved acknowledgements, reminders and follow-up while keeping consultations human-led."}],
  connection:{heading:"Why beauty and wellness services work better together",paragraphs:["A customer may discover a business on Maps, compare services and photos on the website, read reviews and then ask about an appointment on WhatsApp.","Connecting these touchpoints creates a clearer experience and reduces gaps between interest, booking and permitted follow-up."],items:["Local SEO and GBP support nearby discovery","The website explains services under your control","Reputation processes support credible decision-making","WhatsApp workflows support timely customer communication"]},
  process:[{heading:"Discovery",copy:"We understand services, locations, customers, booking methods and current online presence."},{heading:"Strategy",copy:"We map the discovery-to-appointment journey and prioritise the most useful improvements."},{heading:"Implementation",copy:"We deliver the agreed website, local visibility, profile, reputation or communication work."},{heading:"Tracking",copy:"We review available customer actions, profile activity and workflow signals."},{heading:"Improvement",copy:"We refine information and priorities using genuine feedback, business needs and observed behaviour."}],
  expectations:[{heading:"No guaranteed appointments or rankings",copy:"Results depend on location, demand, competition, reputation, pricing, availability and customer experience."},{heading:"Trust grows through consistency",copy:"Profile and website corrections can be completed in phases, while visibility and reputation require ongoing attention."},{heading:"Business input keeps details accurate",copy:"Your team provides approved services, prices, policies, photographs, availability and customer-communication rules."},{heading:"Automation does not replace consultation",copy:"Workflows can support reminders and routing, but suitability advice and sensitive customer conversations remain with trained staff."}],
  faqs:[{q:"What digital marketing is useful for salons and wellness businesses?",a:"A useful foundation often includes a service-led website, Local SEO, Google Business Profile optimisation, genuine review management and clear appointment communication."},{q:"Can Local SEO help a salon appear in nearby searches?",a:"Local SEO can strengthen the website, listings and location signals around relevant searches. It cannot guarantee a specific position, and visibility varies by location and competition."},{q:"How should a salon manage Google reviews?",a:"Use a consistent process to invite genuine feedback, monitor reviews and respond professionally. Reviews should never be fabricated, incentivised improperly or selectively misrepresented."},{q:"Can WhatsApp help with appointment reminders?",a:"Approved reminder and acknowledgement workflows can be useful when customers have provided appropriate consent and the booking process supports them. Staff should handle changes and service questions."},{q:"Do wellness businesses need a website if they use social media?",a:"A website provides an owned, structured place for services, locations, policies and booking actions. Social platforms can support discovery but should not be the only source of business information."}],
  finalCta:{heading:"Review your journey from discovery to appointment",copy:"Request a free audit of your website, local visibility, Google profile, review process and customer communication.",outcomes:["Local visibility gaps","Service and website observations","Profile and reputation review","Prioritised next actions"]}
};

const education:IndustryMoneyPage={
  metadata:{title:"Digital Marketing for Education Businesses in India",description:"Digital growth solutions for Indian coaching institutes and education businesses using websites, SEO, marketing and CRM.",ogTitle:"Turn Student Interest Into Organised Admission Enquiries",ogDescription:"Connect programme discovery, credibility, enquiries and admissions follow-up with DigiUdyam."},
  hero:{heading:"Turn Student Interest Into Clear, Organised Admission Enquiries",paragraphs:["Students and parents need clear information about programmes, eligibility, format, fees, schedules and the next admission step before they enquire.","DigiUdyam helps coaching institutes, training providers and education businesses connect useful website information, search visibility, marketing and CRM follow-up."],needsHeading:"A connected education growth system can help you",needs:["Make programme information easier to understand","Build credibility before an admission conversation","Capture student enquiries with useful context","Organise counselling and follow-up stages"]},
  challenges:[{heading:"Programme information is hard to access",copy:"Scattered course details and unclear next steps create friction for students and parents."},{heading:"Credibility is difficult to evaluate",copy:"Generic claims without transparent faculty, curriculum, process or policy information can weaken trust."},{heading:"Campaign enquiries lack context",copy:"Teams may receive contact details without knowing the programme, location, format or timeline of interest."},{heading:"Admissions follow-up is inconsistent",copy:"Counselling calls and next actions can be missed when enquiries remain across forms, sheets and messaging apps."}],
  journey:[{heading:"Discovery",copy:"A student or parent searches for a course, institute, skill or learning option."},{heading:"Evaluate",copy:"They review the website, search results, programme details, credibility signals and practical information."},{heading:"Enquiry",copy:"They request details, counselling or an application step with relevant context."},{heading:"CRM",copy:"The enquiry is assigned and organised by programme, stage and agreed next action."},{heading:"Follow-up",copy:"The admissions team answers questions and manages the next appropriate counselling or application step."}],
  solutions:[{slug:"website-development",heading:"Website Development",copy:"Structure programmes, faculty information, formats, locations, policies and admission actions clearly."},{slug:"seo",heading:"SEO",copy:"Build useful search-focused pages around programmes and genuine student information needs."},{slug:"digital-marketing",heading:"Digital Marketing",copy:"Plan channels, campaigns, landing pages and measurement around defined admission goals."},{slug:"crm-solutions",heading:"CRM Solutions",copy:"Organise enquiry source, programme interest, ownership, counselling stage and next actions."}],
  connection:{heading:"Why education businesses need visibility and admissions systems together",paragraphs:["Marketing can create awareness, but students still need detailed, credible information before sharing their details or applying.","Connecting useful content, focused campaigns and CRM ownership helps the admissions team continue the conversation with context."],items:["SEO supports relevant programme discovery","The website provides transparent, owned information","Marketing supports selected audiences and admission periods","CRM organises counselling ownership and follow-up"]},
  process:[{heading:"Discovery",copy:"We review programmes, audiences, admission cycles, current channels, content and enquiry handling."},{heading:"Strategy",copy:"We map the search-to-enquiry journey and define priority pages, campaigns and CRM stages."},{heading:"Implementation",copy:"We deliver the agreed website, SEO, marketing, tracking and CRM setup."},{heading:"Tracking",copy:"We review reliable sources, enquiries and pipeline movement without claiming enrolments we cannot verify."},{heading:"Improvement",copy:"We refine pages, campaigns and follow-up using actual questions, admission-team feedback and measured behaviour."}],
  expectations:[{heading:"No guaranteed admissions, leads or rankings",copy:"Outcomes depend on programme quality, demand, reputation, eligibility, pricing, competition and counselling."},{heading:"Search growth takes consistent work",copy:"Website and campaign setup have defined timelines, while organic visibility develops through sustained useful content and technical quality."},{heading:"Education information requires approval",copy:"Your team supplies current curricula, faculty details, schedules, fees, policies and any required disclosures."},{heading:"CRM supports—not replaces—counselling",copy:"The system organises information and actions; qualified staff remain responsible for advice and admission decisions."}],
  faqs:[{q:"Which digital marketing services are useful for coaching institutes?",a:"A clear programme website, SEO, focused digital marketing and an organised admissions CRM are often useful. The right scope depends on programmes, locations, intake cycles and audience."},{q:"Can SEO help students find our courses?",a:"SEO can improve how well useful programme and guidance pages are understood and discovered. It cannot guarantee rankings or admissions, and requires accurate content and sustained improvement."},{q:"What should an education website include?",a:"It should clearly present programmes, audience, curriculum, learning format, faculty information supplied by the institute, locations, schedules, policies and next admission actions."},{q:"How does CRM help an admissions team?",a:"CRM can organise programme interest, source, assigned counsellor, stage, notes and next action so enquiries do not depend on personal memory or separate sheets."},{q:"Do you guarantee student leads or enrolments?",a:"No. Lead and enrolment outcomes depend on the programme, audience, market, budget, counselling and other factors. We focus on clear implementation and measurable customer journeys."}],
  finalCta:{heading:"Find the gaps in your student enquiry journey",copy:"Request a free audit of your website, search presence, marketing journey and admissions follow-up process.",outcomes:["Programme information gaps","Search and website observations","Enquiry-path review","Prioritised admissions actions"]}
};

const professionalServices:IndustryMoneyPage={
  metadata:{title:"Digital Marketing for Professional Services in India",description:"Digital growth solutions for Indian consultants and professional firms using credible websites, SEO, marketing and CRM.",ogTitle:"Build Authority and Generate Better Consultation Enquiries",ogDescription:"Connect expertise, search visibility and organised consultation follow-up with DigiUdyam."},
  hero:{heading:"Turn Professional Expertise Into Visible Trust and Better Enquiries",paragraphs:["Clients often research a professional firm before requesting a consultation. They need to understand the problem you solve, your approach and whether the service fits their situation.","DigiUdyam helps consultants and professional service firms present expertise clearly, improve relevant discovery and organise consultation enquiries without exaggerated authority claims."],needsHeading:"A connected professional-services system can help you",needs:["Explain expertise and services clearly","Build useful search visibility around client problems","Guide suitable prospects towards consultation","Organise ownership and follow-up"]},
  challenges:[{heading:"Expertise is difficult to understand",copy:"Broad service labels and generic copy do not help a prospect see whether the firm can address their specific need."},{heading:"Trust signals are incomplete",copy:"Missing team, process, contact and business information can create doubt before a consultation request."},{heading:"Content lacks a useful search structure",copy:"Insights may exist, but without organised service and educational pages they are difficult to discover."},{heading:"Consultation enquiries lack ownership",copy:"Forms, emails and calls can be missed or duplicated when there is no shared pipeline and next action."}],
  journey:[{heading:"Discovery",copy:"A prospect searches for help with a specific business or professional problem."},{heading:"Evaluate",copy:"They review the website, search content, expertise, process and transparent trust information."},{heading:"Enquiry",copy:"They request a consultation and share enough context for a responsible response."},{heading:"CRM",copy:"The enquiry is assigned, organised and moved through an agreed consultation pipeline."},{heading:"Follow-up",copy:"The right professional reviews the context and completes the next human-led action."}],
  solutions:[{slug:"website-development",heading:"Website Development",copy:"Present services, expertise, people, process and consultation actions in a credible owned experience."},{slug:"seo",heading:"SEO",copy:"Create a technically sound structure for service pages and genuinely useful educational content."},{slug:"digital-marketing",heading:"Digital Marketing",copy:"Plan channels, focused campaigns, landing journeys and measurement around suitable prospects."},{slug:"crm-solutions",heading:"CRM Solutions",copy:"Organise enquiry context, ownership, consultation stage, notes and next actions."}],
  connection:{heading:"Why professional firms need authority and enquiry systems together",paragraphs:["Visibility without clear expertise can attract poor-fit enquiries. Strong content without a consultation process can leave genuine prospects unsure what to do next.","A connected website, search strategy, marketing plan and CRM creates a more credible journey from research to responsible human follow-up."],items:["The website establishes owned business and expertise information","SEO helps useful service guidance become discoverable","Marketing supports defined audiences and goals","CRM keeps consultation ownership and next actions visible"]},
  process:[{heading:"Discovery",copy:"We understand services, audiences, professional boundaries, existing content and consultation workflow."},{heading:"Strategy",copy:"We map the research-to-consultation journey and prioritise trust, visibility and enquiry gaps."},{heading:"Implementation",copy:"We complete the agreed website, SEO, marketing, tracking and CRM work."},{heading:"Tracking",copy:"We review reliable search, enquiry and pipeline signals while respecting confidentiality."},{heading:"Improvement",copy:"We refine priorities using recurring prospect questions, team feedback and measured behaviour."}],
  expectations:[{heading:"No guaranteed enquiries or rankings",copy:"Results depend on demand, competition, reputation, specialisation, pricing and the client’s decision process."},{heading:"Authority is built through useful evidence",copy:"Technical improvements can be completed in phases, while trust and search visibility require accurate, sustained work."},{heading:"The firm approves professional claims",copy:"Your team supplies credentials, service boundaries, people, policies and any industry-specific disclosures."},{heading:"Digital systems do not replace professional judgement",copy:"CRM and workflows organise consultations; qualified professionals remain responsible for advice and client acceptance."}],
  faqs:[{q:"How can a professional service firm generate better enquiries online?",a:"Clearly define services and suitable clients, publish useful information, create a focused consultation path and organise follow-up. Better-fit enquiries depend on clarity as much as traffic."},{q:"Does SEO work for consultants and professional firms?",a:"SEO can help useful service and guidance pages appear for relevant research. It does not guarantee rankings, and success depends on expertise, competition, technical quality and consistent content."},{q:"What trust signals should a professional website include?",a:"Useful signals include accurate company and contact information, real team or founder details, relevant credentials supplied by the firm, a transparent process, service boundaries and clear policies."},{q:"How can CRM improve consultation enquiries?",a:"CRM can record the prospect’s context, source, assigned owner, stage and next action. It supports an organised process while confidential professional information should follow appropriate controls."},{q:"Can you create marketing without making exaggerated claims?",a:"Yes. We focus on clear services, practical process, transparent expertise and useful information. We do not invent credentials, results, testimonials or guarantees."}],
  finalCta:{heading:"Review how prospects discover and evaluate your firm",copy:"Request a free audit of your website, search structure, consultation journey and enquiry follow-up.",outcomes:["Authority and trust gaps","Website and search observations","Consultation-path review","Prioritised next actions"]}
};

const retailShops:IndustryMoneyPage={
  metadata:{title:"Digital Marketing for Retail Shops in India",description:"Digital growth solutions for Indian retail shops using websites, Local SEO, marketing and CRM for discovery and customer communication.",ogTitle:"Help Nearby Customers Discover and Contact Your Retail Shop",ogDescription:"Connect product discovery, store information, enquiries and follow-up with DigiUdyam."},
  hero:{heading:"Help Nearby Customers Discover Your Shop and Products Online",paragraphs:["Customers may search for a product, category or nearby shop before deciding where to visit or whom to message. Clear store information and product visibility make that decision easier.","DigiUdyam helps Indian retail shops connect an owned website, local search, practical marketing and customer-management processes."],needsHeading:"A connected retail growth system can help you",needs:["Make products and categories easier to explore","Improve local discovery for relevant searches","Guide customers towards visits, calls or messages","Organise product enquiries and follow-up"]},
  challenges:[{heading:"The shop is difficult to discover nearby",copy:"Incomplete location, hours and category information can reduce useful visibility across local search."},{heading:"Customers cannot see what is available",copy:"Without clear product categories or current highlights, customers may not know whether the shop fits their need."},{heading:"Information differs across channels",copy:"Old timings, phone numbers or store details create confusion and weaken trust."},{heading:"Customer enquiries remain scattered",copy:"Calls, social messages and WhatsApp questions can be hard to track without ownership or a simple CRM process."}],
  journey:[{heading:"Discovery",copy:"A customer searches for a product, category or local shop, or sees relevant marketing."},{heading:"Evaluate",copy:"They check the website, Google or Maps information, product context, hours and location."},{heading:"Enquiry",copy:"They call, message or ask about availability, suitability or a store visit."},{heading:"CRM",copy:"Where useful, the enquiry is organised by customer, product interest, owner and next action."},{heading:"Follow-up",copy:"The team responds, confirms available information and shares permitted updates or next steps."}],
  solutions:[{slug:"website-development",heading:"Website Development",copy:"Create an owned mobile-friendly place for store information, product categories and customer actions."},{slug:"local-seo",heading:"Local SEO",copy:"Strengthen the connection between the website, store location, listings and relevant local searches."},{slug:"digital-marketing",heading:"Digital Marketing",copy:"Plan channels, campaigns, landing experiences and measurement around specific retail goals."},{slug:"crm-solutions",heading:"CRM Solutions",copy:"Organise product enquiries, customer context, ownership and follow-up where the sales journey requires it."}],
  connection:{heading:"Why retail shops need discovery and customer systems together",paragraphs:["A local search or campaign can introduce the shop, but customers still need accurate details and enough product context to decide whether to visit or enquire.","Connecting discovery, owned information and customer follow-up gives the shop a clearer journey beyond scattered social posts or messages."],items:["Local SEO supports nearby product and store discovery","The website provides structured information under your control","Marketing supports selected categories, occasions or audiences","CRM helps organise enquiries that need continued follow-up"]},
  process:[{heading:"Discovery",copy:"We review store locations, product categories, audiences, current channels and customer communication."},{heading:"Strategy",copy:"We map discovery-to-visit or enquiry journeys and prioritise the most useful information and channels."},{heading:"Implementation",copy:"We deliver the agreed website, search, marketing, tracking and CRM work."},{heading:"Tracking",copy:"We review available website actions, calls, messages and enquiry stages without inventing offline attribution."},{heading:"Improvement",copy:"We update priorities using real customer questions, seasonal needs, stock context and business feedback."}],
  expectations:[{heading:"No guaranteed footfall, leads or rankings",copy:"Results depend on location, products, stock, pricing, competition, service and customer demand."},{heading:"Online visibility needs maintenance",copy:"Website and business-information corrections can be phased; search presence and marketing improve through continued work."},{heading:"The shop keeps product information current",copy:"Your team supplies approved categories, availability context, offers, locations, hours and policies."},{heading:"Digital discovery supports the store experience",copy:"Marketing can help customers find and contact the shop, but availability, service and the in-store experience influence purchase decisions."}],
  faqs:[{q:"How can a retail shop get found by nearby customers?",a:"Use accurate store information, clear product-category pages, consistent listings and a useful local search foundation. The right approach depends on the location and how customers search for the products."},{q:"Does a local retail shop need a website?",a:"A website gives the shop an owned place for categories, locations, hours, enquiries and selected product information. It can complement Google, Maps, marketplaces and social channels."},{q:"Can Local SEO help people find specific products near them?",a:"Local SEO can improve the relevance and consistency of store and category information, but product visibility depends on search demand, content, location and competition. Rankings cannot be guaranteed."},{q:"When is CRM useful for a retail business?",a:"CRM is useful when enquiries need continued follow-up, such as high-consideration products, quotations, special orders or business customers. It may be unnecessary for simple walk-in purchases."},{q:"Can digital marketing guarantee more store visits?",a:"No. Campaigns and visibility can support discovery, but footfall depends on product demand, location, offer, budget and store experience. Measurement should use only reliable online and offline signals."}],
  finalCta:{heading:"Find the gaps in your retail discovery journey",copy:"Request a free audit of your website, local visibility, product discovery and customer enquiry process.",outcomes:["Local discovery gaps","Product-information observations","Customer-action review","Prioritised next steps"]}
};

export const industryMoneyPageMap:Record<string,IndustryMoneyPage>={healthcare:clinics,restaurants,"real-estate":realEstate,"home-services":homeServices,"beauty-wellness":beautyWellness,education,"professional-services":professionalServices,"retail-shops":retailShops};
