import { notFound } from "next/navigation"; import { serviceMap, services } from "@/lib/content"; import { createMetadata, pageMetadata } from "@/lib/metadata"; import { ServicePage } from "@/components/ServicePage";import {serviceRouteAliases} from "@/lib/seo/routes";import {serviceMoneyPageMap} from "@/lib/service-money-pages";
const aliases:Record<string,string>=serviceRouteAliases;
const resolve=(slug:string)=>serviceMap[aliases[slug]||slug];
export function generateStaticParams(){return [...services.map(({slug})=>({slug})),...Object.keys(aliases).map(slug=>({slug}))]}
const seoMetadata:Record<string,{title:string;description:string;keywords:string[]}>= {
  seo:{title:"SEO Services India for Organic Growth",description:"SEO services in India for technical SEO, content optimisation and sustainable national organic rankings. Build search visibility without local SEO overlap.",keywords:["SEO services India","organic search marketing India","SEO agency India","technical SEO India"]},
  "whatsapp-automation":{title:"WhatsApp Marketing Automation India",description:"WhatsApp marketing and follow-up automation for Indian businesses, including approved customer communication, CRM handovers and useful reminders.",keywords:["WhatsApp marketing automation","WhatsApp follow-up automation","customer communication automation"]},
  automation:{title:"Business & Workflow Automation India",description:"Business automation services for Indian MSMEs covering workflow automation, CRM automation, notifications, integrations and controlled handovers.",keywords:["business automation","workflow automation","CRM automation"]},
};
export function generateMetadata({params}:{params:{slug:string}}){const s=resolve(params.slug);if(!s)return {};const path=`/services/${params.slug}`,moneyPage=serviceMoneyPageMap[s.slug],mapped=seoMetadata[s.slug];if(mapped)return createMetadata({...mapped,path});if(moneyPage)return createMetadata({title:moneyPage.metadata.title,description:moneyPage.metadata.description,path,openGraphTitle:moneyPage.metadata.ogTitle,openGraphDescription:moneyPage.metadata.ogDescription});return pageMetadata(`${s.name} for Indian Local Businesses`,`${s.intro} Practical support for Indian local businesses.`,path)}
export default function Page({params}:{params:{slug:string}}){const service=resolve(params.slug);if(!service)notFound();return <ServicePage service={service} canonicalSlug={params.slug}/>}
