"use client";
import { FormEvent,useEffect,useRef,useState } from "react";
import { ArrowUpRight,ChatCircleDots,CheckCircle,X } from "@phosphor-icons/react";
import { usePathname } from "next/navigation";
type Message={id:string;role:"user"|"assistant";content:string};
const welcome:Message={id:"welcome",role:"assistant",content:"Namaste. What would you like to improve in your business’s digital journey? I can help you identify the clearest next step."};
const starters=["Get more local leads","Improve Google visibility","Fix my website","Automate follow-up"];
export function SalesChatWidget(){const path=usePathname();const [open,setOpen]=useState(false),[messages,setMessages]=useState<Message[]>([welcome]),[value,setValue]=useState(""),[loading,setLoading]=useState(false),[qualified,setQualified]=useState(false);const end=useRef<HTMLDivElement>(null);const hidden=path.startsWith("/admin")||path.startsWith("/portal")||path==="/login";
  useEffect(()=>{const token=localStorage.getItem("du-chat-session");if(!token)return undefined;const controller=new AbortController();fetch(`/api/chat?session=${encodeURIComponent(token)}`,{signal:controller.signal}).then(response=>response.ok?response.json():null).then(data=>{if(data?.messages?.length)setMessages([welcome,...data.messages])}).catch(error=>{if(error instanceof Error&&error.name!=="AbortError")console.error("Chat history could not be restored")});return()=>{controller.abort();};},[]);
  useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"});return undefined;},[messages,loading,open]);if(hidden)return null;
  async function submit(content:string){if(!content.trim()||loading)return;setValue("");setMessages(current=>[...current,{id:crypto.randomUUID(),role:"user",content:content.trim()}]);setLoading(true);try{const response=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:content.trim(),session:localStorage.getItem("du-chat-session")})});const data=await response.json();if(data.session)localStorage.setItem("du-chat-session",data.session);if(!response.ok)throw new Error(data.error||"Unable to respond");setMessages(current=>[...current,{id:crypto.randomUUID(),role:"assistant",content:data.reply}]);setQualified(Boolean(data.qualified))}catch(error){setMessages(current=>[...current,{id:crypto.randomUUID(),role:"assistant",content:error instanceof Error?error.message:"I’m unavailable right now. Please try again."}])}finally{setLoading(false)}}
  function send(event:FormEvent){event.preventDefault();void submit(value)}
  const fresh=messages.length===1;
  return <div className={`sales-chat ${open?"open":""}`}><button className="sales-chat-trigger" onClick={()=>setOpen(!open)} aria-label={open?"Close growth desk":"Talk to DigiUdyam growth desk"} aria-expanded={open}>{open?<X/>:<ChatCircleDots weight="fill"/>}<span><small>DIGITAL GROWTH DESK</small><b>Ask DigiUdyam</b></span></button>{open&&<section className="sales-chat-window" role="dialog" aria-label="DigiUdyam growth desk"><header><div className="chat-monogram">DU</div><div><span>DIGITAL GROWTH DESK</span><b>DigiUdyam advisor</b><small><i/> Available now</small></div><button onClick={()=>setOpen(false)} aria-label="Close chat"><X/></button></header><div className="sales-chat-messages" aria-live="polite">{messages.map(message=><article className={message.role} key={message.id}><span>{message.role==="assistant"?"DU":"YOU"}</span><p>{message.content}</p></article>)}{fresh&&<div className="chat-starters"><span>START WITH A GOAL</span>{starters.map(starter=><button onClick={()=>void submit(starter)} key={starter}>{starter}<ArrowUpRight/></button>)}</div>}{loading&&<article className="assistant typing"><span>DU</span><p><i/><i/><i/></p></article>}{qualified&&<div className="chat-qualified"><CheckCircle weight="fill"/><span><b>Details securely saved</b>A consultant can continue with the context you shared.</span></div>}<div ref={end}/></div><form onSubmit={send}><div><label htmlFor="sales-chat-input">Message DigiUdyam</label><textarea id="sales-chat-input" value={value} onChange={event=>setValue(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void submit(value)}}} maxLength={1200} rows={1} placeholder="Ask about your growth…" disabled={loading}/><button disabled={loading||!value.trim()} aria-label="Send message"><ArrowUpRight/></button></div><small>Private conversation · Please don’t share passwords</small></form></section>}</div>}
