import type {Metadata} from "next";import Image from "next/image";import Link from "next/link";import {ArrowRight,Browser,CheckCircle,GoogleLogo,MapPin,Megaphone,Robot,Storefront,UsersThree} from "@phosphor-icons/react/dist/ssr";import {AuditCTA,Breadcrumbs,JsonLd,PageShell} from "@/components/PageShell";import {Container,Eyebrow} from "@/components/ui";import {createMetadata} from "@/lib/metadata";import {aboutPageSchema} from "@/lib/seo/schema";
export const metadata:Metadata={...createMetadata({title:"About DigiUdyam | Digital Growth Partner For Indian MSMEs & Businesses",description:"Learn about DigiUdyam, a digital growth company helping Indian MSMEs and local businesses grow through website development, local SEO, Google Business Profile optimization, digital marketing, CRM and automation solutions.",path:"/about"}),title:{absolute:"About DigiUdyam | Digital Growth Partner For Indian MSMEs & Businesses"}};
const challenges=["Customers cannot easily find them online","Competitors with better digital presence get more attention","Their website does not generate enquiries","Managing leads and customers manually becomes difficult","Digital marketing feels complicated and overwhelming"];
const foundation=["A professional website that builds trust","Local SEO that helps customers discover your business","Google visibility that improves local reach","Marketing strategies that attract potential customers","Systems that help manage enquiries and relationships"];
const questions=["How can I get more customers?","How can people find my business online?","How can I manage enquiries better?","How can I compete with businesses already growing online?"];
const capabilities=[
 {icon:Browser,title:"Professional Websites",paragraphs:["A website is often the first interaction customers have with a business.","We create professional, responsive websites designed to help businesses showcase their services, build trust and generate enquiries."],lead:"Our website solutions are suitable for:",items:["Local businesses","Startups","Clinics","Restaurants","Service providers","Growing companies"],closing:"From starter business websites to advanced custom solutions, we create websites that support business goals.",image:"https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=78",alt:"Professional website development workspace"},
 {icon:MapPin,title:"Local Visibility",paragraphs:["For local businesses, visibility matters.","When customers search for services nearby, appearing in the right places can make a major difference."],lead:"DigiUdyam helps businesses improve their local presence through:",items:["Local SEO strategies","Google Business Profile optimization","Business information improvement","Search visibility enhancement","Customer review strategies"],closing:"Our focus is helping businesses become easier for potential customers to discover.",image:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=78",alt:"Customer visiting an independent local business"},
 {icon:Megaphone,title:"Digital Marketing",paragraphs:["Having an online presence is the first step. Reaching the right audience is what creates growth."],lead:"We help businesses with digital marketing solutions including:",items:["Social media marketing","Paid advertising campaigns","Lead generation strategies","Online growth planning"],closing:"Every marketing activity should connect with a business goal — whether that is more enquiries, more customers or stronger brand visibility.",image:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=78",alt:"Digital marketing performance displayed on a laptop"},
 {icon:Robot,title:"CRM & Automation",paragraphs:["As businesses grow, managing customers manually becomes challenging."],lead:"DigiUdyam helps businesses organize and improve their processes through:",items:["CRM solutions","Lead management","Customer follow-ups","Workflow automation","Business systems"],closing:"The goal is to help businesses save time and create better customer experiences.",image:"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=78",alt:"Business team organizing customers and workflows"}
];
const industryHelp=["Helping shops and service providers create a professional online presence and attract more customers.","Helping clinics and healthcare professionals improve online visibility and make it easier for patients to discover their services.","Helping restaurants showcase their offerings and connect with local customers.","Helping consultants, agencies and service businesses build credibility online.","Helping small and medium businesses adopt websites, marketing systems and automation tools for long-term growth."];
const process=["We learn about your industry, customers, challenges and goals.","We identify the digital solutions that can provide the most value.","We implement websites, SEO, marketing and business systems.","As your business grows, your digital requirements evolve. We help you improve and scale."];
const principles=["We don't believe in providing unnecessary services. We focus on solutions that match your actual business requirements.","Technology should not feel complicated. We explain everything clearly so businesses can make informed decisions.","We understand the challenges small businesses face and create practical solutions suitable for growing businesses.","From website development and SEO to automation and CRM, we help businesses build a stronger digital foundation."];
const clientInputs=["Accurate business, service, location and contact information","Existing brand assets, website access and relevant platform access","Clear goals, priorities, budgets and operational constraints","Timely feedback and approval from the responsible decision-maker","Updates when services, availability, policies or business details change"];
const realisticExpectations=["A clearly defined scope, responsibilities and implementation sequence","Practical recommendations based on the available business context","Transparent separation of setup work, ongoing work, media spend and third-party costs","Measurement using reliable website, platform and enquiry signals where available","No guaranteed rankings, lead volumes, revenue or outcomes outside DigiUdyam’s control"];
export default function About(){return <PageShell><JsonLd data={aboutPageSchema()}/>
 <section className="about-story-hero"><Container><Breadcrumbs items={[{label:"Home",href:"/"},{label:"About"}]}/><div className="about-story-grid"><div><Eyebrow>ABOUT DIGIUDYAM</Eyebrow><h1>Helping Indian Businesses Build a Stronger Digital Presence</h1><p>Every successful business starts with a simple idea — solving a problem for customers. But in today's digital world, having a great product or service is only one part of the journey. Customers are searching online, comparing businesses, reading reviews and making decisions before they ever contact a company.</p><p>DigiUdyam helps Indian MSMEs, local businesses and entrepreneurs build a strong digital foundation that allows them to be discovered, trusted and connected with their customers.</p></div><figure><Image src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1500&q=82" alt="DigiUdyam team discussing digital growth for an Indian business" fill priority sizes="(max-width: 900px) 100vw, 46vw"/><figcaption>BUSINESS FIRST / DIGITAL GROWTH</figcaption></figure></div></Container></section>
 <section className="about-position"><Container><span>ABOUT DIGIUDYAM</span><h2>Who We Are</h2><p className="about-lead">We are a private digital growth company focused on helping businesses move from traditional methods to modern digital solutions through websites, local SEO, Google Business Profile optimization, digital marketing, CRM systems and automation.</p><div><small>Our goal is simple:</small><p>Help businesses establish their online presence, generate more opportunities and grow with practical technology solutions.</p></div></Container></section>
 <section className="about-msme"><Container><div><Eyebrow>Why DigiUdyam exists</Eyebrow><h2>The Opportunity For Indian Businesses</h2><p className="about-lead">India has millions of small businesses, entrepreneurs and MSMEs that contribute significantly to the economy. From local retailers and clinics to restaurants, professionals and service providers, these businesses have valuable products and services to offer.</p><p>However, many businesses face similar challenges:</p></div><div className="about-challenges">{challenges.map((item,i)=><p key={item}><span>0{i+1}</span>{item}</p>)}</div></Container></section>
 <section className="about-belief"><Container><div className="about-belief-image"><Image src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1400&q=80" alt="Independent small business owner serving customers" fill sizes="(max-width: 800px) 100vw, 45vw"/></div><div><Eyebrow>Digital growth should be accessible</Eyebrow><h2>Why We Started DigiUdyam</h2><p className="about-lead">DigiUdyam was created with the idea that digital growth should not be limited to large companies with big budgets.</p><p>Small businesses deserve access to professional websites, better online visibility and modern digital systems that help them compete in today's market.</p><p>We focus on making digital solutions simple, understandable and effective for businesses that want to grow.</p></div></Container></section>
 <section className="about-mission"><Container><div><Eyebrow>What guides our work</Eyebrow><h2>Our Mission</h2><p className="about-lead">Our mission is to help small and growing businesses build a stronger presence online without the confusion that often comes with technology.</p><p>We believe digital growth is not just about creating a website or running advertisements.</p><p>A successful digital presence requires multiple elements working together:</p></div><div>{foundation.map(item=><span key={item}><CheckCircle weight="fill"/>{item}</span>)}</div><p>DigiUdyam brings these solutions together to help businesses create a complete digital growth journey.</p></Container></section>
 <section className="about-objectives"><Container><div><Eyebrow>Business objective first</Eyebrow><h2>Understanding The Bigger Goal</h2><p className="about-lead">Many businesses approach digital marketing looking for a website, SEO or advertising service. But behind every request, there is usually a bigger goal:</p></div><div className="objective-quotes">{questions.map((question,i)=><blockquote key={question}><span>0{i+1}</span>“{question}”</blockquote>)}</div><div className="objective-answer"><p>At DigiUdyam, we focus on understanding the business objective first and then recommend the right digital solution.</p><p>Whether a business needs a simple website to establish credibility or a complete system with SEO, automation and CRM, our approach is based on practical growth.</p></div></Container></section>
 <section className="about-capabilities"><Container><Eyebrow>How we help businesses</Eyebrow>{capabilities.map((capability,i)=><article key={capability.title}><div className="about-cap-image"><Image src={capability.image} alt={capability.alt} fill sizes="(max-width: 800px) 100vw, 40vw" loading="lazy"/><span>0{i+1}</span></div><div><capability.icon weight="duotone"/><h2>{capability.title}</h2>{capability.paragraphs.map(text=><p key={text}>{text}</p>)}<strong>{capability.lead}</strong><div>{capability.items.map(item=><span key={item}><CheckCircle weight="fill"/>{item}</span>)}</div><p>{capability.closing}</p></div></article>)}</Container></section>
 <section className="about-industries"><Container><div><Eyebrow>Businesses we work with</Eyebrow><h2>Industries We Help</h2><p className="about-lead">Every business has unique challenges. A restaurant, clinic, retail store and service company all require different digital strategies.</p><p>DigiUdyam works with:</p></div><div>{industryHelp.map((item,i)=><p key={item}><span>0{i+1}</span>{item}</p>)}</div></Container></section>
 <section className="about-process"><Container><div><Eyebrow>Our approach</Eyebrow><h2>How We Work</h2><p className="about-lead">We understand that many business owners are not looking for complicated technology. They need solutions that are easy to understand and actually help their business.</p><p>Our process focuses on:</p></div><div>{process.map((item,i)=><article key={item}><span>0{i+1}</span><h3>{["Understand Your Business","Identify Opportunities","Build The Solution","Improve And Scale"][i]}</h3><p>{item}</p></article>)}</div></Container></section>
 <section className="about-working-agreement"><Container><div><Eyebrow>A shared working process</Eyebrow><h2>What Clients Provide</h2><p>Good digital work depends on accurate information and timely decisions. DigiUdyam does not invent business details, credentials, offers or customer evidence.</p><div>{clientInputs.map(item=><span key={item}><CheckCircle weight="fill"/>{item}</span>)}</div></div><div><Eyebrow>Clear expectations</Eyebrow><h2>What Clients Should Realistically Expect</h2><p>Digital performance is influenced by the market, competition, offer, budget, customer experience and how consistently the agreed work is implemented.</p><div>{realisticExpectations.map(item=><span key={item}><CheckCircle weight="fill"/>{item}</span>)}</div></div></Container></section>
 <section className="about-principles"><Container><Eyebrow>Practical by design</Eyebrow><h2>What We Believe</h2><div>{principles.map((item,i)=><p key={item}><span>0{i+1}</span>{item}</p>)}</div></Container></section>
 <section className="about-vision"><Container><div><Eyebrow>Our vision</Eyebrow><h2>The future of business is digital.</h2><p>Customers will continue searching online, comparing options and choosing businesses that provide trust and convenience.</p><p>Our vision is to help more Indian MSMEs and local businesses participate in this digital economy by providing accessible, professional and growth-focused digital solutions.</p><p>DigiUdyam aims to become a trusted digital growth partner for businesses that want to build, improve and scale their online presence.</p></div><div className="vision-mark"><GoogleLogo weight="thin"/><Storefront weight="thin"/><UsersThree weight="thin"/><span>DISCOVERED<br/>TRUSTED<br/>CONNECTED</span></div></Container></section>
 <section className="about-final"><Container><p>Whether you are starting your business online or looking to improve your existing digital presence, DigiUdyam can help you identify the right next step.</p><h2>Let's understand your business, your goals and how digital solutions can help you grow.</h2><Link href="/free-audit">Get Your Free Growth Audit Today <ArrowRight/></Link></Container></section>
 <AuditCTA context="your business growth"/>
 </PageShell>}
