import Image from "next/image";
import Link from "next/link";
import { ArrowRight,Check,Envelope,MapPin,Phone,WhatsappLogo } from "@phosphor-icons/react/dist/ssr";
import { Breadcrumbs,JsonLd,PageShell } from "@/components/PageShell";
import { Container,Eyebrow } from "@/components/ui";
import { createMetadata } from "@/lib/metadata";
import { articleSchema,faqSchema,serviceSchema } from "@/lib/seo/schema";
import { site } from "@/lib/site";

const path="/website-development-company-for-small-business-india";
export const metadata=createMetadata({title:"Website Development Company for Small Business India",description:"DigiUdyam is a website development company for small businesses in India. We build affordable, SEO-friendly websites that help businesses attract customers and grow online.",path,image:"/website-development-company-for-small-business-india.webp",keywords:["website development company for small business India","affordable website development","small business website design"]});
const faqs=[{question:"How much does a small business website cost in India?",answer:"The cost depends on website size, features, design requirements, and integrations. Small business websites generally vary based on pages, functionality, and customization."},{question:"How long does it take to build a business website?",answer:"A typical small business website can take around 2-6 weeks depending on requirements, content availability, and revisions."},{question:"Will my website be SEO optimized?",answer:"Yes, websites are built with SEO-friendly structures including proper headings, metadata setup, mobile optimization, and search engine accessibility."},{question:"Can you redesign my existing website?",answer:"Yes, we help businesses redesign outdated websites, improve performance, user experience, and SEO structure."},{question:"Do you provide website maintenance after launch?",answer:"Yes, ongoing maintenance, updates, backups, and technical support options are available."}];
const services=[{title:"Small Business Website Development",intro:"Ideal for:",audience:["Local businesses","Consultants","Service providers","Startups","Professionals"],includes:["Custom website design","5-10 business pages","Mobile responsive layout","Contact forms","Google Analytics setup","Basic SEO optimization"]},{title:"Local Business Website Development",copy:"Designed for businesses targeting local customers.",includes:["Location-based service pages","Google Business Profile integration","Local SEO structure","Review sections","Call and WhatsApp integration"]},{title:"Service-Based Business Websites",intro:"For:",audience:["Healthcare providers","Real estate businesses","Agencies","Professional services"],includes:["Service pages","Lead generation forms","FAQ sections","Trust elements","Conversion optimization"]},{title:"eCommerce Website Development",copy:"For businesses selling products online.",includes:["Shopify/WooCommerce setup","Product pages","Payment integration","Shipping configuration","Product SEO setup"]}];
const process=[{title:"Business Understanding",copy:"We understand your business, customers, competitors, and goals."},{title:"Website Planning",copy:"We create the sitemap, page structure, and user journey."},{title:"Design & Development",copy:"Our team develops a responsive website focused on usability and conversions."},{title:"SEO Setup",copy:"We optimize:",items:["Page structure","Metadata","Speed","Internal linking","Search engine accessibility"]},{title:"Launch & Support",copy:"After launch, we provide technical support and improvements."}];
const industries=[{title:"Healthcare",copy:"Websites for clinics, doctors, and healthcare providers with appointment and enquiry systems.",href:"/industries/clinics"},{title:"Real Estate",copy:"Property websites with listings, enquiry forms, and lead generation features.",href:"/industries/real-estate"},{title:"Beauty & Wellness",copy:"Websites for salons, spas, and wellness brands to attract local customers.",href:"/industries/beauty-wellness"},{title:"Education",copy:"Websites for institutes, coaches, and training providers.",href:"/industries/education"},{title:"Retail & Local Businesses",copy:"Professional websites helping shops and businesses build online visibility.",href:"/industries/retail-shops"}];
const features=["Responsive Design","SEO-Friendly Structure","Contact Forms","WhatsApp Integration","Google Analytics","Speed Optimization","CMS Management","Security Setup"];
const related=[{title:"How Much Does a Website Cost for Small Businesses in India?",href:"/blog/small-business-website-cost-india"},{title:"Why Every Small Business Needs a Website in 2026",href:"/blog/small-business-website-essential-pages"},{title:"Website vs Social Media: What Small Businesses Need",href:"/blog/website-vs-social-media-small-business"}];

export default function Page(){const schemas=[serviceSchema({name:"Website Development Company for Small Business India",description:metadata.description as string,path}),faqSchema(faqs),articleSchema({headline:"Website Development Company for Small Business India",description:metadata.description as string,path,datePublished:"2026-09-01",dateModified:"2026-09-01",authorName:"DigiUdyam Editorial Team",authorType:"Organization",authorId:`${site.url}/#organization`,authorUrl:"/about",image:"/website-development-company-for-small-business-india.webp"})];return <PageShell><JsonLd data={schemas}/><article className="sbw-page">
<header className="sbw-hero"><Container><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Website Development",href:"/services/website-development"},{label:"Website Development Company for Small Business India"}]}/><div className="sbw-hero-grid"><div><Eyebrow>WEBSITE DEVELOPMENT / SMALL BUSINESS INDIA</Eyebrow><h1>Website Development Company for Small Business India</h1><h2>Build a Professional Website That Helps Your Small Business Grow</h2><p>Your website is more than an online presence — it is your digital storefront. DigiUdyam helps small businesses across India create fast, mobile-friendly, and SEO-optimized websites designed to generate trust, attract customers, and support business growth.</p><p>Whether you are a local business, startup, service provider, or growing MSME, we create websites that are built around your goals, customers, and industry requirements.</p><div className="sbw-actions"><Link href="/contact">Get Free Website Consultation <ArrowRight/></Link><Link href="/free-audit">Request Website Audit <ArrowRight/></Link></div></div><figure><Image src="/website-development-company-for-small-business-india.webp" alt="Website development company helping small businesses in India build professional websites" fill priority sizes="(max-width: 900px) 100vw, 46vw"/><figcaption>Professional website solutions help small businesses establish a strong online presence.</figcaption></figure></div></Container></header>
<nav className="sbw-toc" aria-label="Table of contents"><Container><b>TABLE OF CONTENTS</b>{[["Why a website matters","why-websites"],["Website services","services"],["Our process","process"],["Industries served","industries"],["Features","features"],["FAQs","faqs"]].map(([x,id])=><a href={`#${id}`} key={id}>{x}</a>)}</Container></nav>
<section className="sbw-trust"><Container><div><Eyebrow>TRUST / DIGITAL FOUNDATION</Eyebrow><h2>Helping Small Businesses Build Their Digital Presence</h2><p>Small businesses often struggle with:</p><ul>{["Getting discovered online","Building customer trust","Generating consistent enquiries","Competing with larger brands"].map(x=><li key={x}>{x}</li>)}</ul></div><div><p>Our website solutions focus on creating a strong foundation with:</p>{["Professional business design","Mobile-first experience","SEO-ready structure","Fast loading performance","Conversion-focused pages","Easy content management"].map(x=><span key={x}><Check/>{x}</span>)}</div></Container></section>
<section className="sbw-section" id="why-websites"><Container><Heading eyebrow="Why Small Businesses Need a Professional Website" title="Your Website Builds Trust Before Customers Contact You" copy="Today, customers research businesses online before making decisions. A professional website helps your business:"/><div className="sbw-grid">{[["Increase Credibility","A well-designed website shows customers that your business is legitimate and trustworthy."],["Generate More Leads","Strategically placed contact forms, CTAs, and service pages help convert visitors into enquiries."],["Improve Google Visibility","SEO-friendly website structures help search engines understand your services and improve discoverability."],["Compete With Larger Businesses","A strong online presence allows small businesses to compete beyond their local area."]].map(([h,p],i)=><article key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></article>)}</div></Container></section>
<section className="sbw-section sbw-dark" id="services"><Container><Heading light eyebrow="Our Website Development Services for Small Businesses" title="Complete Website Solutions Designed for Growth"/><div className="sbw-grid">{services.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3>{x.copy&&<p>{x.copy}</p>}{x.intro&&<strong>{x.intro}</strong>}{x.audience&&<ul>{x.audience.map(y=><li key={y}>{y}</li>)}</ul>}<strong>Includes:</strong><ul>{x.includes.map(y=><li key={y}><Check/>{y}</li>)}</ul></article>)}</div></Container></section>
<section className="sbw-section sbw-process" id="process"><Container><Heading eyebrow="Our Website Development Process" title="How We Build Websites For Small Businesses"/><div className="sbw-process-grid"><figure><Image src="/small-business-website-development-process-india.webp" alt="Small business website development process including design SEO and launch" fill sizes="(max-width: 900px) 100vw, 45vw"/><figcaption>A structured website development process helps businesses create scalable digital platforms.</figcaption></figure><div>{process.map((x,i)=><article key={x.title}><span>Step {i+1}</span><h3>{x.title}</h3><p>{x.copy}</p>{x.items&&<ul>{x.items.map(y=><li key={y}>{y}</li>)}</ul>}</article>)}</div></div></Container></section>
<section className="sbw-section" id="industries"><Container><Heading eyebrow="Industries We Build Websites For" title="Website Development Solutions Across Industries"/><div className="sbw-industry-grid">{industries.map((x,i)=><Link href={x.href} key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.copy}</p><ArrowRight/></Link>)}</div></Container></section>
<section className="sbw-section sbw-difference"><Container><Heading eyebrow="What Makes DigiUdyam Different?" title="A Website Partner Focused on Business Growth" copy="Unlike template-based website solutions, we focus on:"/><div className="sbw-grid">{[["Business-Focused Strategy","Every website is planned according to your target audience and business goals."],["SEO-Friendly Development","We build websites with search engines and users in mind."],["Conversion-Oriented Design","Every page is structured to encourage enquiries and customer actions."],["Complete Technical Support","Support includes:"]].map(([h,p],i)=><article key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p>{h==="Complete Technical Support"&&<ul>{["Hosting assistance","Website updates","Performance improvements","Technical maintenance"].map(x=><li key={x}>{x}</li>)}</ul>}</article>)}</div></Container></section>
<section className="sbw-section sbw-features" id="features"><Container><Heading eyebrow="Small Business Website Features" title="Everything Required For A Professional Online Presence"/><table><thead><tr><th>Feature</th><th>Included</th></tr></thead><tbody>{features.map(x=><tr key={x}><th>{x}</th><td>✓</td></tr>)}</tbody></table></Container></section>
<section className="sbw-section sbw-faq" id="faqs"><Container><Heading eyebrow="FAQ Section (For SEO)" title="Frequently Asked Questions"/><div>{faqs.map((x,i)=><details key={x.question}><summary><span>0{i+1}</span>{x.question}</summary><p>{x.answer}</p></details>)}</div></Container></section>
<section className="sbw-business"><Container><div><Eyebrow light>AUTHOR / COMPANY INFORMATION</Eyebrow><h2>About DigiUdyam</h2><p>DigiUdyam is a digital solutions company helping businesses grow through website development, SEO, automation and online growth solutions. We provide services to businesses across India with a focus on performance, visibility and measurable results.</p><small>Updated: 1 September 2026 · Website Development</small></div><address><h3>Business Contact Details</h3><a href={`tel:${site.phone}`}><Phone/>{site.phoneDisplay}</a><a href={`https://wa.me/${site.whatsapp}`}><WhatsappLogo/>Chat with our team</a><a href={`mailto:${site.email}`}><Envelope/>{site.email}</a><span><MapPin/>India (Pan-India)</span></address></Container></section>
<nav className="sbw-service-links" aria-label="Related website and SEO services"><Container><Eyebrow>RELATED SERVICES</Eyebrow>{[["Website Development Services","/services/website-development"],["SEO Services","/services/seo"],["Local SEO Services","/services/local-seo"],["Shopify Development","/services/shopify-development"],["Website Maintenance","/services/website-maintenance"]].map(([label,href])=><Link href={href} key={href}>{label}<ArrowRight/></Link>)}</Container></nav>
<section className="sbw-related"><Container><Heading eyebrow="Related Blogs" title="Continue planning your small business website"/><div>{related.map(x=><article key={x.href}><h3>{x.title}</h3><Link href={x.href}>Read related guide <ArrowRight/></Link></article>)}</div></Container></section>
<section className="sbw-cta"><Container><Eyebrow light>BUILD YOUR SMALL BUSINESS WEBSITE</Eyebrow><h2>Build a Professional Website That Helps Your Small Business Grow</h2><p>Tell us about your business, customers, and website goals. DigiUdyam will help you identify the right website structure and next step.</p><div><Link href="/contact">Get Free Website Consultation <ArrowRight/></Link><Link href="/free-audit">Request Website Audit <ArrowRight/></Link></div></Container></section>
</article></PageShell>}

function Heading({eyebrow,title,copy,light=false}:{eyebrow:string;title:string;copy?:string;light?:boolean}){return <header className={light?"sbw-heading light":"sbw-heading"}><Eyebrow light={light}>{eyebrow}</Eyebrow><h2>{title}</h2>{copy&&<p>{copy}</p>}</header>}
