import { CheckCircle, Envelope } from "@phosphor-icons/react/dist/ssr";
import { ContactForm } from "@/components/ContactForm";
import { VisualStoryStrip } from "@/components/VisualStoryStrip";
import { Breadcrumbs, PageShell } from "@/components/PageShell";
import { Container, Eyebrow } from "@/components/ui";
import { pageMetadata } from "@/lib/metadata";
import { site } from "@/lib/site";

export const metadata=pageMetadata("Contact DigiUdyam","Contact DigiUdyam to discuss websites, Google visibility, marketing, CRM and automation for your Indian business.","/contact");
const contactSteps=[{title:"Share the business context",copy:"Tell us about your business, current digital presence and the area where you need clarity."},{title:"Initial review",copy:"The available information is reviewed to understand the main website, visibility, enquiry or workflow gap."},{title:"Clarify the requirement",copy:"If more context is needed, DigiUdyam asks focused questions before recommending a service or scope."},{title:"Receive the next step",copy:"You receive a practical recommendation, and any proposed work should clearly state deliverables, responsibilities and separate costs."}];

export default function Contact(){return <PageShell><section className="contact-page"><Container><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Contact"}]}/><div className="contact-grid"><div className="contact-intro"><Eyebrow>START WITH CLARITY</Eyebrow><h1>Tell us where growth feels stuck.</h1><p>Share your business context and the outcome you are trying to improve. DigiUdyam will use the available information to identify the most useful next conversation.</p><div className="audit-scope"><span>DISCUSSION MAY COVER</span>{["Website","Google visibility","SEO","Marketing","Lead follow-up","Automation"].map((item,index)=><p key={item}><b>0{index+1}</b>{item}</p>)}</div><a href={`mailto:${site.email}`}><Envelope/>{site.email}</a><small>This is DigiUdyam’s currently verified public contact channel. No unverified phone number or address is published.</small></div><ContactForm/></div></Container></section><section className="contact-process"><Container><div><Eyebrow>WHAT HAPPENS NEXT</Eyebrow><h2>A clear enquiry process without an automatic sales promise</h2><p>Response timing depends on the information provided and current availability. Submitting an enquiry does not create a service agreement.</p></div><div>{contactSteps.map((step,index)=><article key={step.title}><span>0{index+1}</span><CheckCircle weight="fill"/><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div></Container></section><VisualStoryStrip type="contact"/></PageShell>}
