import Link from "next/link"; import { ArrowRight, ChartLineUp, CheckCircle, Clock, GoogleLogo, Megaphone, PhoneCall, Robot, Star, UsersThree, Warning } from "@phosphor-icons/react/dist/ssr"; import type { Activity, AttentionItem, JourneyStage, Metric, PulseItem, Status } from "@/lib/portal/types";
const labels:Record<Status,string>={healthy:"Healthy",improving:"Improving",attention:"Needs attention",inactive:"Not active",active:"Active",paused:"Paused",error:"Connection issue"};
export function PortalHeading({eyebrow,title,copy,action}:{eyebrow:string;title:string;copy:string;action?:React.ReactNode}){return <div className="portal-heading"><div><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action}</div>}
export function StatusPill({status}:{status:Status}){return <span className={`status-pill status-${status}`}><i/>{labels[status]}</span>}
export function GrowthPulse({items}:{items:PulseItem[]}){return <section className="pulse-section"><header><div><span>GROWTH PULSE</span><h2>Your digital presence, at a glance.</h2></div><small>Updated from connected sources</small></header><div className="pulse-grid">{items.map(x=><article key={x.id}><span>0{items.indexOf(x)+1}</span><StatusPill status={x.status}/><h3>{x.label}</h3><p>{x.explanation}</p></article>)}</div></section>}
export function AttentionQueue({items}:{items:AttentionItem[]}){return <section className="attention-queue"><header><div><Warning weight="fill"/><span>WHAT NEEDS ATTENTION</span></div><b>{items.length} ITEMS</b></header>{items.map(x=><article key={x.id}><span className={`priority-${x.priority}`}>{x.priority.toUpperCase()}</span><div><h3>{x.title}</h3><p>{x.explanation}</p></div><Link href={x.href}>{x.action}<ArrowRight/></Link></article>)}</section>}
export function GrowthJourney({stages}:{stages:JourneyStage[]}){return <section className="journey-module"><header><span>GROWTH JOURNEY</span><h2>How customers move from finding you to trusting you.</h2></header><div>{stages.map((x,i)=><article key={x.id}><span>0{i+1}</span><strong>{x.count.toLocaleString("en-IN")}</strong><b>{x.label}</b><small>{x.explanation}</small>{i<stages.length-1&&<ArrowRight/>}</article>)}</div></section>}
export function MetricLedger({metrics}:{metrics:Metric[]}){return <section className="metric-ledger"><header><span>KEY NUMBERS / LAST 30 DAYS</span><b>Compared with previous period</b></header><div>{metrics.map((x,i)=><article key={x.id}><span>0{i+1}</span><div><small>{x.label}</small><strong>{x.value}</strong></div><div className="sparkline" aria-label={`${x.label} trend: ${x.trend.join(", ")}`}>{x.trend.map((v,j)=><i key={j} style={{height:`${Math.max(12,v)}%`}}/>)}</div><p><b>{x.change}</b>{x.comparison}</p></article>)}</div></section>}
const activityIcons:Record<string,typeof Star>={review:Star,lead:UsersThree,appointment:Clock,seo:ChartLineUp,automation:Robot,google:GoogleLogo,ads:Megaphone,call:PhoneCall};
export function ActivityFeed({items}:{items:Activity[]}){return <section className="activity-feed"><header><span>RECENT ACTIVITY</span><Link href="/portal/reports">View reports <ArrowRight/></Link></header>{items.map(x=>{const Icon=activityIcons[x.type]||CheckCircle;return <article key={x.id}><Icon weight="duotone"/><div><b>{x.title}</b><small>{x.detail}</small></div><time>{x.time}</time></article>})}</section>}
export function EmptyState({title,copy,action}:{title:string;copy:string;action?:string}){return <div className="empty-state"><span>NO DATA AVAILABLE</span><h3>{title}</h3><p>{copy}</p>{action&&<Link href="/portal/requests">{action}<ArrowRight/></Link>}</div>}
