import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, CheckCircle, Lightning } from "@phosphor-icons/react/dist/ssr";
import { IndustryData, serviceMap } from "@/lib/content";
import { IndustryMoneyPage, industryMoneyPageMap } from "@/lib/industry-money-pages";
import { preferredServiceSlug } from "@/lib/seo/routes";
import { supportingArticlesForIndustry } from "@/lib/seo/internal-links";
import { site } from "@/lib/site";
import { AuditCTA, Breadcrumbs, JsonLd, PageShell } from "./PageShell";
import { Button, Container, Eyebrow } from "./ui";
import { RelatedArticles } from "./RelatedArticles";

function MoneyList({items}:{items:string[]}){return <ul className="money-list">{items.map(item=><li key={item}><Check weight="bold"/><span>{item}</span></li>)}</ul>}

function IndustryMoneyPageView({industry,page,canonicalSlug}:{industry:IndustryData;page:IndustryMoneyPage;canonicalSlug:string}){
  const path=`/industries/${canonicalSlug}`;
  const displayName=canonicalSlug==="clinics"?"Clinics":industry.name;
  const schema={"@context":"https://schema.org","@graph":[{"@type":"Service",name:`Digital growth solutions for ${displayName} in India`,description:page.metadata.description,provider:{"@id":`${site.url}/#organization`},areaServed:{"@type":"Country",name:"India"},audience:{"@type":"Audience",audienceType:`Indian ${displayName.toLowerCase()} and small businesses`},url:`${site.url}${path}`},{"@type":"FAQPage",mainEntity:page.faqs.map(faq=>({"@type":"Question",name:faq.q,acceptedAnswer:{"@type":"Answer",text:faq.a}}))}]};
  return <PageShell><JsonLd data={schema}/>
    <section className="industry-hero industry-money-hero"><Container><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Industries",href:"/industries"},{label:displayName}]}/><header className="detail-hero-title"><Eyebrow>INDUSTRY GROWTH SYSTEM / {displayName}</Eyebrow><h1>{page.hero.heading}</h1></header><div className="industry-hero-grid"><div>{page.hero.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}<div className="money-hero-actions"><Button href="/free-audit">Get a Free Growth Audit</Button><Button variant="secondary" href="#industry-solutions">Explore Recommended Solutions</Button></div></div><div className="industry-hero-image"><Image src={industry.image} alt={`${displayName} business serving local customers in India`} fill priority sizes="(max-width: 900px) 100vw, 48vw"/><div><span>CONNECTED JOURNEY</span><b>Discovery to follow-up</b></div></div></div><aside className="money-needs"><h2>{page.hero.needsHeading}</h2><MoneyList items={page.hero.needs}/></aside></Container></section>
    <div className={`industry-money-page industry-money-${canonicalSlug}`}>
      <section className="money-section money-section-list"><Container><header className="money-section-heading"><span>01 / INDUSTRY CHALLENGES</span><h2>Where the customer journey gets stuck</h2></header><div className="money-section-content"><p>These are common operational and visibility gaps—not assumptions about every business.</p><div className="money-groups">{page.challenges.map(item=><article key={item.heading}><h3>{item.heading}</h3><p>{item.copy}</p></article>)}</div></div></Container></section>
      <section className="money-section money-section-timeline money-section-tint"><Container><header className="money-section-heading"><span>02 / CUSTOMER JOURNEY</span><h2>Connect discovery with the next customer action</h2></header><div className="money-section-content"><p>A practical journey makes it easier for a potential customer to understand the business, enquire and receive a useful response.</p><div className="money-groups">{page.journey.map((item,index)=><article key={item.heading}><h3>{String(index+1).padStart(2,"0")} — {item.heading}</h3><p>{item.copy}</p></article>)}</div></div></Container></section>
      <section className="money-section money-section-list" id="industry-solutions"><Container><header className="money-section-heading"><span>03 / RECOMMENDED SOLUTIONS</span><h2>A connected DigiUdyam system for {displayName.toLowerCase()}</h2></header><div className="money-section-content"><p>Each recommendation has a defined role in the customer journey. The final scope should match the business goal, starting point and available resources.</p><div className="money-groups">{page.solutions.map(item=><article key={item.slug}><h3><Link href={`/services/${preferredServiceSlug(item.slug)}`}>{item.heading} <ArrowRight/></Link></h3><p>{item.copy}</p></article>)}</div></div></Container></section>
      <section className="money-section money-section-tint"><Container><header className="money-section-heading"><span>04 / SERVICE CONNECTION</span><h2>{page.connection.heading}</h2></header><div className="money-section-content">{page.connection.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}<MoneyList items={page.connection.items}/></div></Container></section>
      <section className="money-section money-section-timeline"><Container><header className="money-section-heading"><span>05 / OUR PROCESS</span><h2>From discovery to continuous improvement</h2></header><div className="money-section-content"><p>We define the work in practical phases so responsibilities, approvals and next actions remain clear.</p><div className="money-groups">{page.process.map((item,index)=><article key={item.heading}><h3>{String(index+1).padStart(2,"0")} — {item.heading}</h3><p>{item.copy}</p></article>)}</div></div></Container></section>
      <section className="money-section money-section-cards money-section-tint"><Container><header className="money-section-heading"><span>06 / REALISTIC EXPECTATIONS</span><h2>Clear scope without inflated promises</h2></header><div className="money-section-content"><p>Digital growth is influenced by the offer, market, customer experience, competition, budget and how consistently the agreed work is implemented.</p><div className="money-groups">{page.expectations.map(item=><article key={item.heading}><h3>{item.heading}</h3><p>{item.copy}</p></article>)}</div></div></Container></section>
    </div>
    <section className="service-faq money-faq industry-money-faq"><Container><div><Eyebrow>Industry questions</Eyebrow><h2>Helpful answers for {displayName.toLowerCase()} businesses</h2><p>Practical context before you choose a digital growth approach.</p></div><div>{page.faqs.map((faq,index)=><details key={faq.q}><summary><span>{String(index+1).padStart(2,"0")}</span>{faq.q}</summary><p>{faq.a}</p></details>)}</div></Container></section>
    <section className="industry-services"><Container><Eyebrow>Relevant services</Eyebrow><h2 className="industry-services-title">Explore the services behind this growth system</h2><div>{page.solutions.map(item=><Link href={`/services/${preferredServiceSlug(item.slug)}`} key={item.slug}><span>DIGIUDYAM SERVICE</span><b>{item.heading}</b><ArrowRight/></Link>)}</div><Link className="industry-parent-link" href="/industries">Explore all industries <ArrowRight/></Link></Container></section>
    <RelatedArticles articles={supportingArticlesForIndustry(industry.slug)} heading={`Practical guides for ${displayName.toLowerCase()} businesses`}/>
    <section className="money-final-cta industry-money-final"><Container><div><Eyebrow light>FREE INDUSTRY GROWTH AUDIT</Eyebrow><h2>{page.finalCta.heading}</h2><p>{page.finalCta.copy}</p><div className="money-final-actions"><Button variant="light" href="/free-audit">Request My Free Audit</Button><Button variant="secondary" href="/contact">Talk to DigiUdyam</Button></div></div><aside><h3>What the audit can cover</h3><MoneyList items={page.finalCta.outcomes}/></aside></Container></section>
  </PageShell>;
}

export function IndustryPage({industry,canonicalSlug=industry.slug}:{industry:IndustryData;canonicalSlug?:string}){
  const moneyPage=industryMoneyPageMap[industry.slug];
  if(moneyPage)return <IndustryMoneyPageView industry={industry} page={moneyPage} canonicalSlug={canonicalSlug}/>;
  const path=`/industries/${canonicalSlug}`;const schema={"@context":"https://schema.org","@type":"Service",name:`Digital growth services for ${industry.name}`,description:industry.intro,provider:{"@type":"Organization",name:site.name,url:site.url},areaServed:{"@type":"Country",name:"India"},url:`${site.url}${path}`};return <PageShell><JsonLd data={schema}/><section className="industry-hero"><Container><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Industries",href:"/industries"},{label:industry.name}]}/><header className="detail-hero-title"><Eyebrow>INDUSTRY SYSTEM / {industry.name}</Eyebrow><h1>{industry.headline}</h1></header><div className="industry-hero-grid"><div><p>{industry.intro}</p><Link className="text-link" href="/contact">Plan my growth system <ArrowRight/></Link></div><div className="industry-hero-image"><Image src={industry.image} alt={`${industry.name} business environment`} fill priority sizes="(max-width: 800px) 100vw, 48vw"/><div><span>NEW ENQUIRY</span><b>Customer journey captured</b></div></div></div></Container></section><section className="industry-friction"><Container><div><span>01 / COMMON FRICTION</span><h2>Where growth gets stuck.</h2></div><div>{industry.problems.map((x,i)=><p key={x}><b>0{i+1}</b>{x}<span>NEEDS ATTENTION</span></p>)}</div></Container></section><section className="journey-section"><Container><Eyebrow>The customer journey</Eyebrow><h2>Make each decision easier.</h2><div className="journey-track">{industry.journey.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><i/><b>{x}</b>{i<industry.journey.length-1&&<ArrowRight/>}</div>)}</div></Container></section><section className="recommended-system"><Container><div className="system-photo"><Image src={industry.image} alt="" fill sizes="(max-width: 800px) 100vw, 40vw"/></div><div><Eyebrow>Recommended system</Eyebrow><h2>Built around the way {industry.name.toLowerCase()} customers choose.</h2>{industry.system.map(x=><p key={x}><CheckCircle weight="fill"/>{x}</p>)}</div></Container></section><section className="industry-automation"><Container><div><Lightning weight="duotone"/><span>PRACTICAL AUTOMATION</span></div><h2>{industry.automation}</h2><p>Automation supports the conversation. Your team stays in control whenever judgement or a human response matters.</p></Container></section><section className="industry-services"><Container><Eyebrow>Relevant capabilities</Eyebrow><div>{industry.services.map(slug=><Link href={`/services/${preferredServiceSlug(slug)}`} key={slug}><span>{serviceMap[slug].kicker.split("/")[0]}</span><b>{serviceMap[slug].name}</b><ArrowRight/></Link>)}</div></Container></section><RelatedArticles articles={supportingArticlesForIndustry(industry.slug)} heading={`Practical guides for ${industry.name.toLowerCase()} businesses`}/><AuditCTA context={`${industry.name.toLowerCase()} growth`}/></PageShell>;
}
