import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, Check, Circle, Pulse } from "@phosphor-icons/react/dist/ssr";
import { ServiceData, industryMap, serviceMap } from "@/lib/content";
import { RichText, ServiceMoneyPage, serviceMoneyPageMap } from "@/lib/service-money-pages";
import { site } from "@/lib/site";
import { preferredIndustrySlug, preferredServiceSlug } from "@/lib/seo/routes";
import { supportingArticlesForService } from "@/lib/seo/internal-links";
import { AuditCTA, Breadcrumbs, JsonLd, PageShell, TextLink } from "./PageShell";
import { RelatedArticles } from "./RelatedArticles";
import { Button, Container, Eyebrow } from "./ui";

const visualSets:Record<string,{src:string;alt:string}[]>={
  website:[{src:"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=78",alt:"Website strategy and design workspace for a growing business"},{src:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=78",alt:"Business team reviewing a website project together"},{src:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=78",alt:"Business performance dashboard displayed on a laptop"}],
  local:[{src:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=78",alt:"Local shop owner helping a customer at the counter"},{src:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=78",alt:"Local search visibility performance being reviewed"},{src:"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=78",alt:"Local business team planning customer growth"}],
  pipeline:[{src:"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=78",alt:"Sales team collaborating around a customer pipeline"},{src:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=78",alt:"CRM sales performance dashboard on a computer"},{src:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=78",alt:"Account team discussing customer follow-up"}],
  default:[{src:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=78",alt:"Digital growth team discussing a business plan"},{src:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=78",alt:"Marketing results and business data on a laptop"},{src:"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=78",alt:"Team working together on a customer growth workflow"}]
};

const heroImages:Record<string,{src:string;alt:string;label:string}>={
  "web-development":{src:"https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1400&q=82",alt:"Website developer building a modern business website on a computer",label:"WEBSITE DESIGN & DEVELOPMENT"},
  seo:{src:"https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1400&q=82",alt:"SEO specialist reviewing website search performance and analytics",label:"SEARCH VISIBILITY & INSIGHTS"},
  "local-seo":{src:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1400&q=82",alt:"Customer visiting an independent local business discovered online",label:"LOCAL DISCOVERY"},
  "google-business-profile":{src:"https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1400&q=82",alt:"Local business owner serving a customer at the shop counter",label:"LOCAL BUSINESS PRESENCE"},
  "google-ads":{src:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=82",alt:"Digital advertising campaign performance displayed on a laptop",label:"CAMPAIGNS & LEAD TRACKING"},
  "reputation-management":{src:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82",alt:"Business team reviewing customer feedback and service quality",label:"CUSTOMER TRUST & REVIEWS"},
  crm:{src:"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82",alt:"Sales team collaborating on customer relationships and follow-ups",label:"LEADS & CUSTOMER MANAGEMENT"},
  "whatsapp-automation":{src:"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=82",alt:"Business communication and customer follow-up managed from digital devices",label:"MESSAGING & FOLLOW-UP"},
  "ai-automation":{src:"https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1400&q=82",alt:"Modern automation technology supporting business workflows",label:"PRACTICAL BUSINESS AUTOMATION"}
};

function ServiceVisual({service,displayName=service.name}:{service:ServiceData;displayName?:string}){const image=heroImages[service.slug]||visualSets.default[0];return <figure className="service-hero-photo"><Image src={image.src} alt={image.alt} fill priority sizes="(max-width: 900px) 100vw, 48vw"/><div className="service-photo-shade"/><figcaption><span>{"label" in image?image.label:"BUSINESS GROWTH"}</span><b>{displayName}</b><small>{service.outcomes[0]}</small></figcaption></figure>}

function RichTextView({content}:{content:RichText}){
  if(typeof content==="string")return <>{content}</>;
  return <>{content.map((part,index)=>typeof part==="string"?part:<Link href={part.href} key={`${part.href}-${index}`}>{part.text}</Link>)}</>;
}

function MoneyPageList({items}:{items:string[]}){return <ul className="money-list">{items.map(item=><li key={item}><Check weight="bold"/><span>{item}</span></li>)}</ul>}

function MoneyServicePage({service,page,canonicalSlug}:{service:ServiceData;page:ServiceMoneyPage;canonicalSlug:string}){
  const displayName=service.slug==="web-development"?"Website Development":service.slug==="crm"?"CRM Solutions":service.name;
  const schema={"@context":"https://schema.org","@graph":[{"@type":"Service",name:service.slug==="crm"?"CRM Solutions":service.name,description:page.metadata.description,provider:{"@type":"Organization",name:site.name,url:site.url},areaServed:{"@type":"Country",name:"India"},url:`${site.url}/services/${canonicalSlug}`},{"@type":"FAQPage",mainEntity:page.faqs.map(faq=>({"@type":"Question",name:faq.q,acceptedAnswer:{"@type":"Answer",text:[faq.a,...(faq.items||[])].join(" ")}}))}]};
  return <PageShell><JsonLd data={schema}/>
    <section className="inner-hero service-hero money-hero"><Container><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:displayName}]}/><header className="detail-hero-title"><Eyebrow>{service.kicker}</Eyebrow><h1>{page.hero.heading}</h1></header><div className="inner-hero-grid"><div>{page.hero.paragraphs.map(x=><p key={x}>{x}</p>)}<div className="money-hero-actions"><Button href={page.hero.primaryCta.href}>{page.hero.primaryCta.label}</Button><Button variant="secondary" href={page.hero.secondaryCta.href}>{page.hero.secondaryCta.label}</Button></div></div><ServiceVisual service={service} displayName={displayName}/></div><aside className="money-needs" aria-labelledby="money-needs-title"><h2 id="money-needs-title">{page.hero.needsHeading}</h2><MoneyPageList items={page.hero.needs}/></aside></Container></section>
    <div className={`money-page-body money-page-${service.slug}`}>{page.sections.map((section,index)=><section className={`money-section money-section-${section.presentation||"cards"} ${index%2?"money-section-tint":""}`} id={section.id} key={section.heading}><Container><header className="money-section-heading"><span>{String(index+1).padStart(2,"0")}</span><h2>{section.heading}</h2></header><div className="money-section-content">{section.paragraphs?.map((paragraph,i)=><p key={i}><RichTextView content={paragraph}/></p>)}{section.items&&<MoneyPageList items={section.items}/>} {section.table&&<div className="money-table-wrap"><table><thead><tr>{section.table.headings.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{section.table.rows.map(row=><tr key={row[0]}><th scope="row">{row[0]}</th><td>{row[1]}</td></tr>)}</tbody></table></div>}{section.groups&&<div className="money-groups">{section.groups.map((group,i)=><article className={!group.heading?"money-group-continuation":""} key={`${group.heading}-${i}`}>{group.heading&&<h3>{group.heading}</h3>}{group.paragraphs?.map((paragraph,j)=><p key={j}><RichTextView content={paragraph}/></p>)}{group.items&&<MoneyPageList items={group.items}/>}</article>)}</div>}{section.cta&&<Button href={section.cta.href}>{section.cta.label}</Button>}</div></Container></section>)}</div>
    <section className="service-faq money-faq"><Container><div><Eyebrow>Frequently Asked Questions</Eyebrow><h2>Frequently Asked Questions</h2></div><div>{page.faqs.map((faq,i)=><details key={faq.q}><summary><span>{String(i+1).padStart(2,"0")}</span>{faq.q}</summary><p>{faq.a}</p>{faq.items&&<MoneyPageList items={faq.items}/>}</details>)}</div></Container></section>
    <section className="related-field"><Container><div><Eyebrow>Related services</Eyebrow><h2>Continue building your digital growth system</h2></div><div className="related-links">{service.slug==="web-development"&&<TextLink href="/website-development-for-healthcare-business">Healthcare Website Development</TextLink>}{service.related.map(slug=><TextLink href={`/services/${preferredServiceSlug(slug)}`} key={slug}>{serviceMap[slug].name}</TextLink>)}</div><div className="industry-links"><span>RELEVANT FOR</span>{service.industries.map(slug=><Link href={`/industries/${preferredIndustrySlug(slug)}`} key={slug}>{industryMap[slug].name}</Link>)}</div></Container></section>
    <RelatedArticles articles={supportingArticlesForService(service.slug)} heading={`Practical guides for ${displayName.toLowerCase()} decisions`}/>
    <section className="money-final-cta"><Container><div><Eyebrow light>{page.finalCta.eyebrow||"Website project discussion"}</Eyebrow><h2>{page.finalCta.heading}</h2>{page.finalCta.paragraphs.map(x=><p key={x}>{x}</p>)}<div className="money-final-actions"><Button variant="light" href={page.finalCta.primaryCta.href}>{page.finalCta.primaryCta.label}</Button><Button variant="secondary" href={page.finalCta.secondaryCta.href}>{page.finalCta.secondaryCta.label}</Button></div><p className="money-contact-line"><RichTextView content={page.finalCta.contactText}/></p></div><aside><h3>{page.finalCta.subheading}</h3><MoneyPageList items={page.finalCta.fields}/></aside></Container></section>
  </PageShell>;
}

export function ServicePage({service,canonicalSlug=service.slug}:{service:ServiceData;canonicalSlug?:string}){
  const moneyPage=serviceMoneyPageMap[service.slug];
  if(moneyPage)return <MoneyServicePage service={service} page={moneyPage} canonicalSlug={canonicalSlug}/>;
  const faqs=[{q:`How do I know if ${service.name} is right for my business?`,a:`We first review your current presence, customer journey and main goal. We recommend ${service.name} only when it supports a clear business outcome.`},{q:`What does your ${service.name} process include?`,a:"The work begins with discovery and an audit, moves into a focused plan and implementation, and continues with measurement and practical improvements."},{q:"How long does it take to see progress?",a:"Timelines depend on your starting point, competition and scope. We explain immediate deliverables, ongoing work and the signals used to measure progress."},{q:"Do you guarantee rankings or leads?",a:"No responsible partner can guarantee a Google position or exact lead volume. We focus on sound implementation, useful measurement and transparent reporting."}];
  const schema={"@context":"https://schema.org","@graph":[{"@type":"Service",name:service.name,description:service.intro,provider:{"@type":"Organization",name:site.name,url:site.url},areaServed:{"@type":"Country",name:"India"},url:`${site.url}/services/${canonicalSlug}`},{"@type":"FAQPage",mainEntity:faqs.map(x=>({"@type":"Question",name:x.q,acceptedAnswer:{"@type":"Answer",text:x.a}}))}]};
  return <PageShell><JsonLd data={schema}/>
    <section className="inner-hero service-hero"><Container><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:service.name}]}/><header className="detail-hero-title"><Eyebrow>{service.kicker}</Eyebrow><h1>{service.headline}</h1></header><div className="inner-hero-grid"><div><p>{service.intro}</p><div className="inner-hero-links"><Link href="/free-audit">Get a free growth audit <ArrowRight/></Link><Link href="#method">See our process <ArrowDown/></Link></div></div><ServiceVisual service={service}/></div></Container></section>
    <section className="service-thesis"><Container><div className="thesis-index">01 / WHY IT MATTERS</div><div><h2>{service.problem}</h2><p>We connect the work around a clear customer journey—not a disconnected list of marketing tasks.</p></div></Container></section>
    <section className="outcome-ledger"><Container><div className="ledger-title"><Eyebrow>Benefits</Eyebrow><h2>Business outcomes first.</h2></div><div className="ledger-list">{service.outcomes.map((x,i)=><div key={x}><span>0{i+1}</span><Check weight="bold"/><b>{x}</b></div>)}</div></Container></section>
    <section className="capability-field"><Container><div><Eyebrow>What we may deliver</Eyebrow><h2>A solution shaped around the goal.</h2><p>We recommend only what supports the goal. Aapko unnecessary tools nahi milenge.</p></div><div className="capability-list">{service.capabilities.map((x,i)=><span key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</span>)}</div></Container></section>
    <section className="service-system" id="method"><Container><div className="system-label"><span>02 / OUR METHODOLOGY</span><Pulse/><b>CONNECTED</b></div><h2>{service.name} is not one task.<br/>It is a working sequence.</h2><div className="service-steps">{service.steps.map((x,i)=><article key={x.title}><span>0{i+1}</span><Circle weight="fill"/><h3>{x.title}</h3><p>{x.copy}</p>{i<service.steps.length-1&&<ArrowRight/>}</article>)}</div></Container></section>
    <section className="service-faq"><Container><div><Eyebrow>Helpful answers</Eyebrow><h2>Questions business owners ask.</h2><p>Clear expectations before you make a decision.</p></div><div>{faqs.map((faq,i)=><details key={faq.q}><summary><span>0{i+1}</span>{faq.q}</summary><p>{faq.a}</p></details>)}</div></Container></section>
    <section className="related-field"><Container><div><Eyebrow>Continue exploring</Eyebrow><h2>Useful next capabilities</h2><p><Link href="/blog">Read practical growth guides</Link> or <Link href="/contact">talk to our team</Link>.</p></div><div className="related-links">{service.related.map(slug=><TextLink href={`/services/${preferredServiceSlug(slug)}`} key={slug}>{serviceMap[slug].name}</TextLink>)}</div><div className="industry-links"><span>RELEVANT FOR</span>{service.industries.map(slug=><Link href={`/industries/${preferredIndustrySlug(slug)}`} key={slug}>{industryMap[slug].name}</Link>)}</div></Container></section>
    <RelatedArticles articles={supportingArticlesForService(service.slug)} heading={`Practical guides related to ${service.name.toLowerCase()}`}/>
    <AuditCTA context={service.name.toLowerCase()}/>
  </PageShell>
}
