import type{Metadata}from"next";import Image from"next/image";import Link from"next/link";import{ArrowRight,Browser,CheckCircle,GoogleLogo,MapPin,Megaphone,Robot,UsersThree}from"@phosphor-icons/react/dist/ssr";import{AuditCTA,Breadcrumbs,JsonLd,PageShell}from"@/components/PageShell";import{Container,Eyebrow}from"@/components/ui";import{createMetadata}from"@/lib/metadata";import{faqSchema}from"@/lib/seo/schema";
export const metadata:Metadata={...createMetadata({title:"Digital Marketing & Website Development Services For Indian Businesses | DigiUdyam",description:"DigiUdyam provides website development, local SEO, Google Business Profile optimization, digital marketing, CRM and automation solutions to help Indian MSMEs and small businesses grow online.",path:"/services"}),title:{absolute:"Digital Marketing & Website Development Services For Indian Businesses | DigiUdyam"}};
const serviceSections=[
 {id:"website",icon:Browser,title:"Website Development",paragraphs:["Your website is more than an online brochure. It is your digital identity and often the first impression customers have of your business.","DigiUdyam creates modern, responsive websites designed for Indian businesses that want to establish credibility, showcase their services and generate customer enquiries."],lead:"Our website development solutions include:",items:["Business websites","Service-based websites","Landing pages","Mobile responsive design","WhatsApp integration","Contact forms","Basic SEO setup","Conversion-focused layouts"],after:"For small businesses starting their digital journey, we provide professional 5-page websites that help establish a strong online presence.",sublead:"Suitable for:",secondary:["Local shops","Clinics","Restaurants","Salons","Consultants","Service providers"],href:"/services/website-development",image:"https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1400&q=80",alt:"Professional website development for an Indian business"},
 {id:"local-seo",icon:MapPin,title:"Local SEO",paragraphs:["For local businesses, visibility matters.","When customers search for services near them, businesses that appear prominently have a better chance of receiving enquiries.","DigiUdyam helps improve local search visibility through strategic local SEO solutions."],lead:"Our local SEO services include:",items:["Local keyword research","Website SEO improvements","Google Business Profile optimization","Location-based optimization","Business information consistency","Local search strategy","Performance tracking"],after:"Whether you run a clinic, restaurant, shop or service business, local SEO helps connect you with customers who are actively looking for your services.",href:"/services/local-seo",image:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1400&q=80",alt:"Local business serving a customer who discovered it online"},
 {id:"google-profile",icon:GoogleLogo,title:"Google Business Profile",paragraphs:["Your Google Business Profile is one of the most important digital assets for a local business."],lead:"A properly optimized profile helps customers:",items:["Discover your business","Understand your services","View reviews","Contact you easily","Get directions"],after:"DigiUdyam helps businesses optimize their Google presence through:",secondary:["Profile setup and optimization","Business category improvement","Service and product updates","Profile content optimization","Review improvement strategies","Local visibility guidance"],href:"/services/google-business-profile",image:"https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1400&q=80",alt:"Local business profile helping customers visit a shop"},
 {id:"marketing",icon:Megaphone,title:"Digital Marketing",paragraphs:["Having a digital presence is only the beginning. Businesses need effective strategies to reach potential customers.","DigiUdyam provides digital marketing solutions focused on visibility, engagement and lead generation."],lead:"Our solutions include:",items:["Build stronger connections with your audience through strategic content and social media presence.","Reach potential customers through targeted advertising campaigns on platforms like:","Google Ads","Meta Ads","Create campaigns designed to attract potential customers and generate business enquiries."],after:"Our focus is not just getting views or clicks — it is helping businesses create meaningful growth opportunities.",href:"/services/digital-marketing",image:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=80",alt:"Digital marketing visibility and lead generation performance"},
 {id:"crm",icon:UsersThree,title:"CRM Solutions",paragraphs:["Many businesses lose opportunities because customer enquiries are not managed properly.","A CRM system helps businesses organize customer relationships and improve follow-ups."],lead:"DigiUdyam helps businesses implement systems for:",items:["Lead management","Customer tracking","Sales pipeline management","Follow-up reminders","Team collaboration","Customer relationship management"],after:"A better system helps businesses respond faster and create better customer experiences.",href:"/services/crm-solutions",image:"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=80",alt:"Business team managing leads and customer relationships"},
 {id:"automation",icon:Robot,title:"Business Automation",paragraphs:["As businesses grow, repetitive tasks consume valuable time.","Automation helps businesses streamline processes and focus on growth."],lead:"Our automation solutions include:",items:["WhatsApp automation","Lead follow-up workflows","Customer notifications","Business process automation","Integration solutions"],after:"We help businesses reduce manual work and create smoother operations.",href:"/services/automation",image:"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=80",alt:"Connected digital devices supporting business automation"}
];
const bundles=[{title:"A new business may need:",services:"Website + Google Business Profile"},{title:"A growing local business may need:",services:"Website + SEO + Marketing"},{title:"An established business may need:",services:"SEO + CRM + Automation"}];
const industries=["Improve online visibility and help patients discover your services.","Build a stronger digital presence and attract more local customers.","Help customers discover your products and connect with your business.","Generate better enquiries and showcase properties professionally.","Build credibility and attract more students.","Create a trusted online presence and generate opportunities."];
const principles=["We understand the challenges faced by small businesses and provide practical solutions.","We focus on your goals instead of offering unnecessary services.","No confusing technical language. We keep the process clear and transparent.","Start with what your business needs today and expand as you grow.","From websites and SEO to automation and CRM, we help businesses build a stronger digital foundation."];
const process=["We learn about your business, customers and goals.","We recommend the digital services that match your requirements.","We create and implement your digital growth solutions.","We analyze performance and improve your digital presence over time."];
const faqs=[{question:"What services does DigiUdyam provide?",answer:"DigiUdyam provides website development, local SEO, Google Business Profile optimization, digital marketing, CRM solutions and business automation services for Indian businesses."},{question:"How much does a website cost?",answer:"Website costs depend on requirements, design and features. DigiUdyam offers starter business websites from ₹7,000 for businesses beginning their online journey."},{question:"Does digital marketing help small businesses?",answer:"Yes. Digital marketing helps businesses reach customers where they spend their time — online. It can improve visibility, enquiries and customer growth."},{question:"What is local SEO?",answer:"Local SEO helps businesses appear when customers search for nearby services. It is especially useful for clinics, restaurants, shops and service providers."},{question:"Can DigiUdyam improve my Google presence?",answer:"Yes. DigiUdyam helps businesses improve their Google presence through Google Business Profile optimization and local SEO strategies."},{question:"Does DigiUdyam provide complete growth solutions?",answer:"Yes. DigiUdyam provides complete digital growth solutions including websites, SEO, marketing, CRM and automation."}];
export default function Services(){return <PageShell><JsonLd data={faqSchema(faqs)}/>
 <section className="services-story-hero"><Container><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Services"}]}/><div><Eyebrow>DIGITAL GROWTH SERVICES</Eyebrow><h1>Your customers are already searching online. The question is — can they find your business?</h1><p>DigiUdyam helps Indian MSMEs, local businesses and entrepreneurs build a stronger digital presence through professional websites, local SEO, Google visibility, digital marketing, automation and customer management solutions.</p><p>We don't believe every business needs the same solution. We understand your goals, challenges and industry first, then create a digital strategy that helps your business attract more customers and grow.</p><p>From building your first website to creating complete digital systems, DigiUdyam provides practical solutions designed for businesses at every stage.</p></div></Container></section>
 <section className="services-foundation"><Container><div><Eyebrow>A connected approach</Eyebrow><h2>A successful online presence requires more than just one service.</h2></div><div><p>A website creates credibility. SEO helps customers discover you. Marketing brings opportunities. Automation helps you manage growth.</p><p>DigiUdyam combines different digital solutions to help businesses create a complete growth system.</p><nav aria-label="Service sections">{serviceSections.map((service,i)=><a href={`#${service.id}`} key={service.id}><span>0{i+1}</span>{service.title}</a>)}</nav></div></Container></section>
 <div className="services-detail-list">{serviceSections.map((service,i)=><section id={service.id} className="services-detail" key={service.id}><Container><figure><Image src={service.image} alt={service.alt} fill sizes="(max-width: 850px) 100vw, 43vw" loading={i===0?undefined:"lazy"}/><span>0{i+1}</span></figure><div><service.icon weight="duotone"/><h2>{service.title}</h2>{service.paragraphs.map(text=><p key={text}>{text}</p>)}<strong>{service.lead}</strong><div className="services-checks">{service.items.map(item=><span key={item}><CheckCircle weight="fill"/>{item}</span>)}</div><p>{service.after}</p>{service.sublead&&<strong>{service.sublead}</strong>}{service.secondary&&<div className="services-checks secondary">{service.secondary.map(item=><span key={item}><CheckCircle weight="fill"/>{item}</span>)}</div>}<Link href={service.href}>View {service.title}<ArrowRight/></Link></div></Container></section>)}</div>
 <section className="service-bundles"><Container><div><Eyebrow>Solutions for every stage</Eyebrow><h2>Many businesses need more than one service.</h2><p>For example:</p></div><div>{bundles.map((bundle,i)=><article key={bundle.title}><span>0{i+1}</span><p>{bundle.title}</p><h3>{bundle.services}</h3></article>)}</div><p>DigiUdyam creates solutions based on your business stage and growth goals.</p></Container></section>
 <section className="services-industries"><Container><div><Eyebrow>Industry-focused solutions</Eyebrow><h2>Every industry has different customers and challenges.</h2><p>We create strategies based on your business requirements.</p></div><div>{industries.map((item,i)=><p key={item}><span>0{i+1}</span>{item}</p>)}</div></Container></section>
 <section className="services-principles"><Container><Eyebrow>Why DigiUdyam</Eyebrow><div>{principles.map((item,i)=><p key={item}><span>0{i+1}</span>{item}</p>)}</div></Container></section>
 <section className="services-process"><Container><div><Eyebrow>Our process</Eyebrow><h2>Clear steps. Practical execution.</h2></div><div>{process.map((item,i)=><article key={item}><span>0{i+1}</span><h3>{["Understand","Recommend","Create","Improve"][i]}</h3><p>{item}</p></article>)}</div></Container></section>
 <section className="home-faq services-faq"><Container><div><Eyebrow>Frequently asked questions</Eyebrow><h2>Helpful answers for business owners.</h2></div><div>{faqs.map((faq,i)=><details key={faq.question}><summary><span>0{i+1}</span>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></Container></section>
 <section className="services-closing"><Container><h2>Your customers are already searching. Let DigiUdyam help you build a stronger digital presence and create new growth opportunities.</h2><Link href="/free-audit">Get Your Free Growth Audit <ArrowRight/></Link></Container></section>
 <AuditCTA context="your digital growth"/></PageShell>}
