import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Briefcase, CalendarBlank, Envelope, Globe, MapPin, Phone, User } from "@phosphor-icons/react/dist/ssr";
import { getLeadDetail } from "@/lib/admin/crm-service";
import { getOnboardingOptions } from "@/lib/admin/onboarding-service";
import { addLeadActivityAction, archiveLeadAction, changeLeadStageAction, convertLeadAction, updateLeadAction } from "@/app/admin/crm/actions";
import "../crm.css";
import "./lead-detail.css";

const stages=[{v:"new_lead",l:"New Lead"},{v:"contacted",l:"Contacted"},{v:"qualified",l:"Qualified"},{v:"proposal_sent",l:"Proposal Sent"},{v:"negotiation",l:"Negotiation"},{v:"won",l:"Won"},{v:"lost",l:"Lost"}];
export async function generateMetadata({params}:{params:{leadId:string}}){const {lead}=await getLeadDetail(params.leadId);return {title:lead?`${lead.business_name} · CRM`:"Lead"}}

export default async function LeadDetail({params}:{params:{leadId:string}}) {
  const [{lead,activities,owners,services},onboarding]=await Promise.all([getLeadDetail(params.leadId),getOnboardingOptions()]); if(!lead)notFound();
  const owner=owners.find(item=>item.id===lead.sales_owner_id);
  const specialists=onboarding.staff.filter(member=>member.role==="specialist");
  return <div className="admin-page lead-workspace">
    <div className="lead-detail-head"><div><Link href="/admin/crm"><ArrowLeft/> LEAD DIRECTORY</Link><span>{lead.status.replaceAll("_"," ")}</span><h1>{lead.business_name}</h1><p>{lead.name} · Created {new Date(lead.created_at).toLocaleDateString("en-IN")}</p></div><form action={changeLeadStageAction}><input type="hidden" name="id" value={lead.id}/><label>Pipeline stage<select name="status" defaultValue={lead.status}>{stages.map(stage=><option key={stage.v} value={stage.v}>{stage.l}</option>)}</select></label><button>Update stage</button></form></div>
    <section className="lead-facts"><article><User/><span>CONTACT</span><b>{lead.name}</b><small>{owner?.full_name?`Owner: ${owner.full_name}`:"Sales owner unassigned"}</small></article><article><Envelope/><span>EMAIL</span><b>{lead.email||"Not provided"}</b><small>{lead.phone||"No phone"}</small></article><article><Briefcase/><span>DEAL VALUE</span><b>₹{Number(lead.pipeline_value).toLocaleString("en-IN")}</b><small>{lead.lead_source}</small></article><article><CalendarBlank/><span>FOLLOW-UP</span><b>{lead.follow_up_at?new Date(lead.follow_up_at).toLocaleDateString("en-IN"):"Not scheduled"}</b><small>{lead.follow_up_at?new Date(lead.follow_up_at).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"}):"Set a next action"}</small></article></section>
    <div className="lead-detail-grid"><section className="lead-information"><header>BUSINESS & CONTACT INFORMATION</header><div><p><Globe/><span>Website</span><b>{lead.website||"Not provided"}</b></p><p><MapPin/><span>Location</span><b>{lead.location||"Not provided"}</b></p><p><Briefcase/><span>Industry</span><b>{lead.industry||"Not specified"}</b></p><p><Phone/><span>Phone</span><b>{lead.phone||"Not provided"}</b></p></div><form action={updateLeadAction}><input type="hidden" name="id" value={lead.id}/><label>Contact name<input name="name" defaultValue={lead.name} required/></label><label>Business name<input name="business_name" defaultValue={lead.business_name} required/></label><label>Email<input name="email" type="email" defaultValue={lead.email||""}/></label><label>Phone<input name="phone" defaultValue={lead.phone||""}/></label><label>Website<input name="website" defaultValue={lead.website||""}/></label><label>Industry<input name="industry" defaultValue={lead.industry||""}/></label><label>Location<input name="location" defaultValue={lead.location||""}/></label><label>Lead source<input name="lead_source" defaultValue={lead.lead_source} required/></label><label>Deal value<input name="pipeline_value" type="number" min="0" defaultValue={lead.pipeline_value}/></label><label>Follow-up<input name="follow_up_at" type="datetime-local" defaultValue={lead.follow_up_at?.slice(0,16)||""}/></label><label>Sales owner<select name="sales_owner_id" defaultValue={lead.sales_owner_id||""}><option value="">Unassigned</option>{owners.map(item=><option value={item.id} key={item.id}>{item.full_name}</option>)}</select></label><label className="wide">Internal notes<textarea name="notes" rows={5} defaultValue={lead.notes||""}/></label><button>Save changes</button></form></section>
      <section className="lead-activity-panel"><header>ACTIVITY TIMELINE</header><form action={addLeadActivityAction}><input type="hidden" name="lead_id" value={lead.id}/><select name="activity_type"><option value="note">Note</option><option value="call">Call</option><option value="email">Email</option><option value="follow_up">Follow-up</option></select><textarea name="summary" required placeholder="Record the outcome or next step" rows={3}/><button>Add activity</button></form><div>{activities.length?activities.map(activity=><article key={activity.id}><i/><div><span>{activity.activity_type.replaceAll("_"," ")}</span><p>{activity.summary}</p><time>{new Date(activity.occurred_at).toLocaleString("en-IN")}</time></div></article>):<p className="crm-inline-empty">No activities recorded yet.</p>}</div></section></div>
    {lead.status==="won"&&!lead.converted_organization_id&&<form action={convertLeadAction} className="lead-convert lead-convert-workspace"><input type="hidden" name="lead_id" value={lead.id}/><h3>Convert this deal into a client</h3><p>This creates the organization, business, primary location, secure client invitation, service assignments and existing onboarding workflow.</p><label>Primary location<input name="location_name" defaultValue={lead.location||"Primary location"} required/></label><label>Timezone<input name="timezone" defaultValue="Asia/Kolkata"/></label><label>Account manager<select name="account_manager_id" defaultValue={lead.sales_owner_id||""}>{owners.map(item=><option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label><fieldset><legend>Services</legend>{services.map(service=><label key={service.id}><input type="checkbox" name="service_ids" value={service.id}/>{service.name}</label>)}</fieldset><fieldset><legend>Specialists</legend>{specialists.map(member=><label key={member.id}><input type="checkbox" name="specialist_ids" value={member.id}/>{member.full_name}</label>)}</fieldset><button className="admin-primary">Create client and start onboarding</button></form>}
    {lead.converted_organization_id&&<section className="lead-converted"><b>Converted client workspace</b><p>This lead remains linked to its original client record.</p><Link href={`/admin/clients/${lead.converted_organization_id}`}>Open client workspace</Link></section>}
    <form action={archiveLeadAction} className="lead-archive"><input type="hidden" name="id" value={lead.id}/><button>Archive lead</button></form>
  </div>;
}
