import "server-only";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { requireAdmin } from "./auth";
import { onboardClient } from "./onboarding-service";
import type { Database } from "@/lib/supabase/database.types";
import { emitNotificationSafe } from "@/lib/notifications/service";
type LeadInsert=Database["public"]["Tables"]["leads"]["Insert"];type LeadUpdate=Database["public"]["Tables"]["leads"]["Update"];

export async function getCrmData(query="",status="all") {await requireAdmin("manage_leads");const db=createSupabaseServerClient();let q=db.from("leads").select("*").is("archived_at",null).order("updated_at",{ascending:false});if(query)q=q.or(`name.ilike.%${query.slice(0,80)}%,business_name.ilike.%${query.slice(0,80)}%,email.ilike.%${query.slice(0,80)}%,phone.ilike.%${query.slice(0,80)}%`);if(status!=="all")q=q.eq("status",status as any);const [leads,activities,owners,services]=await Promise.all([q.limit(300),db.from("lead_activities").select("*").order("occurred_at",{ascending:false}).limit(300),db.from("profiles").select("id,full_name,role,status").in("role",["super_admin","admin","account_manager"]).eq("status","active").order("full_name"),db.from("services").select("id,name").eq("active",true).order("name")]);const failure=[leads,activities,owners,services].find(x=>x.error);if(failure?.error)throw failure.error;return {leads:leads.data||[],activities:activities.data||[],owners:owners.data||[],services:services.data||[]}}
export async function getLeadDetail(id:string){await requireAdmin("manage_leads");const db=createSupabaseServerClient();const [lead,activities,owners,services]=await Promise.all([db.from("leads").select("*").eq("id",id).is("archived_at",null).maybeSingle(),db.from("lead_activities").select("*").eq("lead_id",id).order("occurred_at",{ascending:false}),db.from("profiles").select("id,full_name,role,status").in("role",["super_admin","admin","account_manager"]).eq("status","active").order("full_name"),db.from("services").select("id,name").eq("active",true).order("name")]);const failure=[lead,activities,owners,services].find(x=>x.error);if(failure?.error)throw failure.error;return {lead:lead.data,activities:activities.data||[],owners:owners.data||[],services:services.data||[]}}
export async function createLead(values:Omit<LeadInsert,"created_by">){const actor=await requireAdmin("manage_leads");const db=createSupabaseServerClient();const {data,error}=await db.from("leads").insert({...values,created_by:actor.userId}).select().single();if(error)throw error;await db.from("lead_activities").insert({lead_id:data.id,actor_id:actor.userId,activity_type:"note",summary:"Lead created"});await emitNotificationSafe({event:"lead_created",recipientIds:[data.sales_owner_id||actor.userId],title:`New lead: ${data.business_name}`,body:`${data.name} was added from ${data.lead_source}.`,severity:"info"});return data}
export async function updateLead(id:string,values:LeadUpdate){await requireAdmin("manage_leads");const db=createSupabaseServerClient();const {data:before,error:readError}=await db.from("leads").select("business_name,sales_owner_id").eq("id",id).single();if(readError)throw readError;const {error}=await db.from("leads").update(values).eq("id",id);if(error)throw error;if(values.sales_owner_id&&values.sales_owner_id!==before.sales_owner_id)await emitNotificationSafe({event:"lead_assigned",recipientIds:[values.sales_owner_id],title:`Lead assigned: ${before.business_name}`,body:"You are now responsible for this sales opportunity."})}
export async function changeLeadStatus(id:string,status:LeadUpdate["status"]){const actor=await requireAdmin("manage_leads");const db=createSupabaseServerClient();const {data:lead,error:readError}=await db.from("leads").select("status,business_name,sales_owner_id").eq("id",id).single();if(readError)throw readError;const {error}=await db.from("leads").update({status}).eq("id",id);if(error)throw error;await db.from("lead_activities").insert({lead_id:id,actor_id:actor.userId,activity_type:"status_change",summary:`Stage changed from ${lead.status} to ${status}`,metadata:{from:lead.status,to:status||""}});await emitNotificationSafe({event:"lead_status_changed",recipientIds:[lead.sales_owner_id||actor.userId],title:`${lead.business_name} moved to ${String(status).replaceAll("_"," ")}`,body:`Pipeline stage changed from ${lead.status.replaceAll("_"," ")}.`})}
export async function addLeadActivity(input:{leadId:string;type:"call"|"email"|"note"|"follow_up";summary:string}){const actor=await requireAdmin("manage_leads");const {error}=await createSupabaseServerClient().from("lead_activities").insert({lead_id:input.leadId,actor_id:actor.userId,activity_type:input.type,summary:input.summary});if(error)throw error}
export async function archiveLead(id:string){await updateLead(id,{archived_at:new Date().toISOString()})}
export async function deleteLead(id:string){await requireAdmin("manage_leads");const {error}=await createSupabaseServerClient().from("leads").delete().eq("id",id);if(error)throw error}
export async function convertLeadToClient(input:{leadId:string;locationName:string;timezone:string;serviceIds:string[];accountManagerId?:string;specialistIds:string[]}){const actor=await requireAdmin("manage_leads");const db=createSupabaseServerClient();const {data:lead,error}=await db.from("leads").select("*").eq("id",input.leadId).is("converted_organization_id",null).single();if(error||!lead)throw error||new Error("Lead already converted");if(!lead.email)throw new Error("A client email is required before conversion");const result=await onboardClient({organizationName:lead.business_name,primaryContactName:lead.name,clientEmail:lead.email,businessName:lead.business_name,industry:lead.industry||undefined,locationName:input.locationName||lead.location||"Primary location",city:lead.location||undefined,timezone:input.timezone||"Asia/Kolkata",serviceIds:input.serviceIds,accountManagerId:input.accountManagerId||lead.sales_owner_id||actor.userId,specialistIds:input.specialistIds});await db.from("leads").update({status:"won",converted_organization_id:result.organizationId}).eq("id",lead.id);await db.from("lead_activities").insert({lead_id:lead.id,actor_id:actor.userId,activity_type:"status_change",summary:"Lead converted to client",metadata:{organization_id:result.organizationId}});return result}
